from __future__ import annotations

import json
import os
import shutil

import pytest

from agentforge.interfaces.cli.main import run_create


@pytest.fixture
def clean_generated_projects():
    """Fixture to ensure the generated_projects folder is cleaned up."""
    if os.path.exists("generated_projects"):
        shutil.rmtree("generated_projects", ignore_errors=True)
    yield
    if os.path.exists("generated_projects"):
        shutil.rmtree("generated_projects", ignore_errors=True)


def test_agentforge_create_generates_all_artifacts(clean_generated_projects) -> None:
    idea = (
        "Build a secure FastAPI task manager with PostgreSQL, Docker, "
        "tests, and documentation"
    )

    # Run CLI creation
    output = run_create(idea, as_json=True)
    payload = json.loads(output)

    # Verify summary result details
    assert payload["status"] == "completed"
    assert "plan" in payload["executed_node_ids"]
    assert "01_project_brief" in payload["executed_node_ids"]
    assert len(payload["executed_node_ids"]) == 11

    # Verify output path is returned and structured correctly
    output_path = payload.get("output_path")
    assert output_path is not None
    assert output_path.startswith("generated_projects/")

    # Verify the output folder actually exists
    assert os.path.isdir(output_path)

    # Verify that all 10 required markdown files are created
    required_files = [
        "01_Project_Brief.md",
        "02_Functional_Requirements.md",
        "03_Non_Functional_Requirements.md",
        "04_Feasibility_Study.md",
        "05_System_Architecture.md",
        "06_Technology_Stack.md",
        "07_Implementation_Plan.md",
        "08_Testing_Strategy.md",
        "09_Deployment_Plan.md",
        "10_Risk_Assessment.md",
    ]

    for filename in required_files:
        filepath = os.path.join(output_path, filename)
        assert os.path.isfile(filepath), f"Missing file: {filename}"

        # Read content and verify it contains content based on the user idea
        with open(filepath, encoding="utf-8") as f:
            content = f.read()

        assert content.strip().startswith("#"), (
            f"File {filename} does not start with markdown title heading."
        )

        # Metadata checks (header format)
        assert "Project Name:" in content
        assert "Generated By: AgentForge Orchestrator" in content
        assert "Workflow ID: " in content
        assert "Version: 1.0.0" in content
        assert "Status: Approved" in content
        assert "Last Updated:" in content

        # Verify length requirements
        length = len(content)
        if filename in ["02_Functional_Requirements.md", "05_System_Architecture.md"]:
            assert length >= 3000, (
                f"File {filename} is too short: {length} chars (min 3000)."
            )
        else:
            assert length >= 1500, (
                f"File {filename} is too short: {length} chars (min 1500)."
            )

        # Content-specific assertions
        if filename == "02_Functional_Requirements.md":
            assert "FR-001" in content
            assert "Acceptance Criteria" in content
            assert "Authorization Matrix" in content
            assert "API Endpoint Specifications" in content
            assert "POST" in content
            assert "Request and Response Examples" in content
            assert "Business and Validation Rules" in content
        elif filename == "03_Non_Functional_Requirements.md":
            assert "NFR-001" in content
            assert "Verification Method" in content
            assert "Success Threshold" in content
            assert "Failure Threshold" in content
            assert "Verification Environment" in content
            assert "Monitoring Signal" in content
        elif filename == "04_Feasibility_Study.md":
            assert "Technical Feasibility" in content
            assert "Operational Feasibility" in content
            assert "Economic Feasibility" in content
            assert "Schedule Feasibility" in content
            assert "Feasibility Scoring Table" in content
            assert "|" in content
            assert "Weighted Score" in content
            assert "GO" in content
        elif filename == "05_System_Architecture.md":
            assert "```mermaid" in content
            assert "C4-Style System Context Diagram" in content
            assert "Container Diagram" in content
            assert "Component Diagram" in content
            assert "Deployment Diagram" in content
            assert "Architectural Decision Records" in content
            assert "Database Indexing Notes" in content
            assert "Security Threat Model Summary" in content
        elif filename == "06_Technology_Stack.md":
            assert "FastAPI" in content
            assert "PostgreSQL" in content
            assert "Docker" in content
            assert "pytest" in content
            assert "0.110.0" in content
            assert "16.0" in content
            assert "24.0.0" in content
            assert "8.0.0" in content
            assert "Dependency Categories" in content
            assert "Alternatives Considered and Decision Rationale" in content
        elif filename == "10_Risk_Assessment.md":
            assert "Risk ID" in content
            assert "|" in content


def test_run_create_non_json_output(clean_generated_projects) -> None:
    idea = (
        "Build a secure FastAPI task manager with PostgreSQL, Docker, "
        "tests, and documentation"
    )
    output = run_create(idea, as_json=False)

    assert "Workflow:" in output
    assert "Status: completed" in output
    assert "Output path: generated_projects/" in output
