"""Agent plugins for generating professional-grade project planning artifacts."""

from __future__ import annotations

from datetime import datetime

from agentforge.domain.entities import Artifact, ProjectTask
from agentforge.domain.value_objects import Capability, RiskLevel
from agentforge.runtime.plugins.contracts import (
    AgentExecutionStatus,
    AgentMetadata,
    AgentResult,
)


def get_metadata_header(project_name: str, doc_title: str) -> str:
    """Generate a consistent document metadata header."""
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""---
Project Name: {project_name}
Document: {doc_title}
Generated By: AgentForge Orchestrator
Workflow ID: {{{{workflow_id}}}}
Version: 1.0.0
Status: Approved
Last Updated: {now_str}
---"""


class BriefAgentPlugin:
    """Agent that generates the Project Brief artifact."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.brief",
            name="Brief Agent",
            version="0.1.0",
            capabilities=(Capability("project-brief-generation"),),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        meta = get_metadata_header(task.description, "01_Project_Brief")
        content = f"""# Project Brief

{meta}

## 1. Executive Summary
This document serves as the official project brief for the software project:
"{task.description}".
The goal of this initiative is to plan and construct a robust system that fulfills
all core functionalities while adhering to modern architectural practices. By using
capability-driven design, we isolate responsibilities and establish a baseline for
reliable service delivery.

## 2. Project Vision
The vision is to deliver a production-ready application tailored to:
"{task.description}".
It will act as a reference implementation of a high-quality service, featuring clean
separation of concerns, secure access control, and highly maintainable components.
The system will run reliably in containerized environments and support straightforward
monitoring and debugging.

## 3. Problem Statement
Many current software implementations suffer from tight coupling, lack of unit test
coverage, and incomplete deployment configurations. This makes maintaining and scaling the
application complex and error-prone. The implementation of "{task.description}" solves
these issues by enforcing a structured architecture from the outset, backed by relational
durability and containerization.

## 4. Goals and Objectives
- Establish a clean, well-tested codebase with at least 90% test coverage.
- Deliver an automated, containerized deployment environment using Docker.
- Ensure all API endpoints are fully documented, secure, and performant.
- Provide persistent storage with transactional safety.

## 5. Target Users
- **System Administrators**: Responsible for deployment, monitoring, and scaling.
- **Application Developers**: Tasked with extending and maintaining the codebase.
- **End Users**: Accessing the API endpoints for task management and authentication.

## 6. Assumptions and Constraints
- **Assumptions**: The system will run on a Unix-like host or Docker container.
- **Constraints**: Deployment must fit within standard small-scale hosting parameters.

## 7. Scope of Work
- Implementation of secure authentication and authorization handlers.
- Development of core domain logic models and database migrations.
- Automation of testing suites and continuous integration pipelines.
- Container infrastructure provisioning.

## 8. Out-of-Scope Items
- Mobile client application development.
- Third-party payment gateway integration.
- Custom machine learning analytics engines.
- Multi-region database clustering.

## 9. High-Level Modules
- **Authentication**: JWT validation, security policies, and user registration.
- **Core Domain Manager**: Creation, retrieval, update, and deletion workflows.
- **Persistence Layer**: DB connections, migrations, and model definitions.
- **Infrastructure Setup**: Docker configuration and deployment playbooks.

## 10. Success Criteria
- Execution of all test suites completes without warnings or errors.
- Successful builds of all Docker containers.
- API response times stay below 200ms for 99% of requests.
- Zero critical security vulnerability findings.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary="Generated project brief artifact.",
            artifacts=(Artifact(name="01_Project_Brief.md", content=content),),
            confidence=0.9,
        )


class RequirementsAgentPlugin:
    """Agent that generates functional and non-functional requirements."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.requirements",
            name="Requirements Agent",
            version="0.1.0",
            capabilities=(
                Capability("requirements-analysis"),
                Capability("non-functional-requirements-analysis"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        caps = {c.name for c in task.required_capabilities}
        if "requirements-analysis" in caps:
            name = "02_Functional_Requirements.md"
            meta = get_metadata_header(task.description, "02_Functional_Requirements")
            content = f"""# Functional Requirements

{meta}

## 1. Document Purpose
This document specifies the complete functional requirements for the software system:
"{task.description}".
It establishes the baseline for development, testing, and eventual system acceptance.

## 2. System Overview
The system provides a capability-driven backend service implementing core task and user
management workflows. Key capabilities include secure OAuth2 token issuance, relational
persistence, task manipulation, validation, and containerization.

## 3. Actors and Users
- **Anonymous User**: Can register a new account and request OAuth2 login tokens.
- **Authenticated User**: Can manage their own tasks and retrieve their profile information.
- **Administrator**: Can perform global operations, including removing orphaned resources.

## 4. Authorization Matrix
The following matrix defines resource access permissions:

| Role | User Register | Token Exchange | Create Task | View Own Tasks | View All Tasks |
|------|---------------|----------------|-------------|----------------|----------------|
| Anon | Yes           | Yes            | No          | No             | No             |
| User | No            | No             | Yes         | Yes            | No             |
| Admin| No            | No             | Yes         | Yes            | Yes            |

## 5. API Endpoint Specifications
The backend service exposes the following endpoints:

| Method | Endpoint | Description | Auth Required |
|--------|----------|-------------|---------------|
| POST | `/api/v1/auth/register` | Register a new user account | No |
| POST | `/api/v1/auth/token` | Exchange credentials for JWT token | No |
| GET | `/api/v1/users/me` | Retrieve current user profile | Yes |
| POST | `/api/v1/tasks` | Create a new task entity | Yes |
| GET | `/api/v1/tasks` | List and filter user tasks | Yes |
| PUT | `/api/v1/tasks/{{id}}` | Update a task details/status | Yes |
| DELETE | `/api/v1/tasks/{{id}}` | Remove a task entity | Yes |

## 6. Request and Response Examples

### User Registration (POST `/api/v1/auth/register`)
- **Request Payload**:
```json
{{
  "username": "johndoe",
  "email": "john@example.com",
  "password": "SuperSecurePassword123!"
}}
```
- **Response Payload (HTTP 201 Created)**:
```json
{{
  "id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "username": "johndoe",
  "email": "john@example.com",
  "created_at": "2026-06-30T00:00:00Z"
}}
```

### Create Task (POST `/api/v1/tasks`)
- **Request Payload**:
```json
{{
  "title": "Complete Project Architecture",
  "description": "Formulate and document system architectural diagrams.",
  "priority": "high"
}}
```
- **Response Payload (HTTP 201 Created)**:
```json
{{
  "id": "b1b2b3b4-c5c6-d7d8-e9e0-f1f2f3f4f5f6",
  "title": "Complete Project Architecture",
  "description": "Formulate and document system architectural diagrams.",
  "priority": "high",
  "status": "pending",
  "due_date": null,
  "created_at": "2026-06-30T00:05:00Z"
}}
```

## 7. Business and Validation Rules

### Business Rules
- **BR-001**: Task Ownership. Users can only read, write, update, or delete tasks associated
  with their authenticated user ID. Attempting to modify tasks of others returns HTTP 403.
- **BR-002**: Token Validity. Access tokens must expire after 30 minutes, necessitating exchange.

### Validation Rules per Entity
- **User Validation**:
  - `username` must be alphanumeric, containing 3 to 50 characters.
  - `email` must match standard RFC 5322 format.
  - `password` must contain at least 8 characters, including a digit and a special symbol.
- **Task Validation**:
  - `title` is required, with length between 1 and 100 characters.
  - `priority` must match one of: `low`, `medium`, `high`.
  - `status` must match one of: `pending`, `in_progress`, `completed`.

## 8. Edge Cases and Mitigations
- **EC-001**: Concurrent Database Modifications.
  - *Mitigation*: Employ optimistic concurrency control using version flags.
- **EC-002**: Database Connection Drop.
  - *Mitigation*: Implement resilient SQL connection retries with exponential backoff.

## 9. Requirement Specifications

### FR-001: User Account Registration
- **Description**: The system must allow users to register an account with a unique username,
  email address, and strong password.
- **Priority**: High
- **Acceptance Criteria**:
  - Registration fails if username or email already exists.
  - Hashing of passwords must use secure bcrypt algorithm.
  - Return HTTP 201 Created on successful registration.

### FR-002: User Authentication & Token Generation
- **Description**: Users must be able to exchange username and password for a JWT token.
- **Priority**: High
- **Acceptance Criteria**:
  - Accept valid credentials and return a signed JSON Web Token (JWT).
  - Return HTTP 401 Unauthorized for incorrect passwords or missing accounts.
  - JWT must include standard expiration time of 30 minutes.

### FR-003: Task Creation (CRUD)
- **Description**: Authenticated users must be able to create new tasks with title,
  description, priority level, and due date.
- **Priority**: High
- **Acceptance Criteria**:
  - Title field is mandatory and must not be empty.
  - Return HTTP 201 Created with the serialized task object.
  - Associate task with the authenticated user ID.

### FR-004: Task Retrieval & List Filtering
- **Description**: Users must be able to list their tasks, filtering by status, priority,
  and due date.
- **Priority**: Medium
- **Acceptance Criteria**:
  - List only returns tasks belonging to the authenticated user.
  - Allow sorting by due date in ascending/descending order.
  - Return HTTP 200 OK with the array of tasks.

### FR-005: Task Modification
- **Description**: Users must be able to update properties of an existing task.
- **Priority**: High
- **Acceptance Criteria**:
  - Reject updates to tasks owned by other users with HTTP 403 Forbidden.
  - Allow marking task as completed, which records a completed timestamp.
  - Return HTTP 200 OK with the updated task.

### FR-006: Task Deletion
- **Description**: Users must be able to delete a task.
- **Priority**: High
- **Acceptance Criteria**:
  - Restrict deletion to the owner of the task.
  - Return HTTP 204 No Content upon successful deletion.

### FR-007: User Profile Retrieve
- **Description**: Authenticated users must be able to retrieve their profile information.
- **Priority**: Low
- **Acceptance Criteria**:
  - Exclude the password hash from the serialized JSON payload.
  - Return HTTP 200 OK.

## 10. Traceability Matrix

| Req ID | Capability / Module | Test Case ID | Target Release |
|--------|---------------------|--------------|----------------|
| FR-001 | User Registration   | TC-AUTH-001  | v1.0.0         |
| FR-002 | OAuth2 Login        | TC-AUTH-002  | v1.0.0         |
| FR-003 | Task CRUD           | TC-TASK-001  | v1.0.0         |
| FR-004 | Task Filtering      | TC-TASK-002  | v1.0.0         |
| FR-005 | Task Update         | TC-TASK-003  | v1.0.0         |
| FR-006 | Task Delete         | TC-TASK-004  | v1.0.0         |
| FR-007 | Profile Fetch       | TC-AUTH-003  | v1.0.0         |
"""
        else:
            name = "03_Non_Functional_Requirements.md"
            meta = get_metadata_header(task.description, "03_Non_Functional_Requirements")
            content = f"""# Non-Functional Requirements

{meta}

## 1. Measurable NFR Specifications

### NFR-001: API Performance & Response Latency
- **Category**: Performance
- **Priority**: High
- **Success Threshold**: p95 response time < 200ms under normal load conditions.
- **Failure Threshold**: p95 response time > 500ms under any load conditions.
- **Verification Environment**: Staging Environment
- **Verification Method**: Execute automated load tests using Locust with 100 concurrent users.
- **Monitoring Signal**: Prometheus metric `http_request_duration_seconds` histogram bucket.

### NFR-002: Transport Layer Security (TLS)
- **Category**: Security
- **Priority**: High
- **Success Threshold**: 100% of external traffic using TLS 1.3 protocol.
- **Failure Threshold**: Support of SSLv3, TLS 1.0, or TLS 1.1 protocol.
- **Verification Environment**: Staging & Production Environments
- **Verification Method**: Validate server SSL certificates using automated scanning tools.
- **Monitoring Signal**: Traefik ingress logs detailing protocol version per TLS handshake.

### NFR-003: Password Hashing Integrity
- **Category**: Security
- **Priority**: High
- **Success Threshold**: Passwords must be hashed using bcrypt with a work factor of 12.
- **Failure Threshold**: Hash functions with work factor less than 10 or using MD5/SHA1 algorithms.
- **Verification Environment**: Development & CI Environments
- **Verification Method**: Static code analysis and unit tests verifying the hashing configuration.
- **Monitoring Signal**: CI code audit logs and test suite summaries.

### NFR-004: System Availability & Uptime
- **Category**: Reliability
- **Priority**: High
- **Success Threshold**: Monthly uptime of 99.9% or higher.
- **Failure Threshold**: Monthly uptime below 99.0%.
- **Verification Environment**: Production Environment
- **Verification Method**: Monitor availability using continuous HTTP pinging probes.
- **Monitoring Signal**: Grafana availability panel based on ping probes.

### NFR-005: Horizontal Scalability
- **Category**: Scalability
- **Priority**: Medium
- **Success Threshold**: Scale seamlessly from 2 to 10 container replicas.
- **Failure Threshold**: Container CPU throttling or memory starvation leading to restart.
- **Verification Environment**: Staging Environment
- **Verification Method**: Deploy 3 concurrent Docker replicas behind a round-robin load balancer.
- **Monitoring Signal**: Kubernetes replica set count and pod status indicators.

### NFR-006: Maintainability & Code Quality
- **Category**: Maintainability
- **Priority**: High
- **Success Threshold**: Zero errors detected by Ruff and MyPy tools.
- **Failure Threshold**: Codebase containing syntax warnings or ignored lint issues.
- **Verification Environment**: Continuous Integration Pipeline
- **Verification Method**: Run Ruff style checks and mypy type checks.
- **Monitoring Signal**: GitHub Actions build outcome indicator.

## 2. NFR Verification Matrix

| NFR ID | Category | Priority | Success Threshold | Verification Env | Verification Method |
|--------|----------|----------|-------------------|------------------|---------------------|
| NFR-001| Perf     | High     | p95 < 200ms       | Staging          | Locust Load Tests   |
| NFR-002| Security | High     | TLS 1.3 only      | Production       | SSL Scan            |
| NFR-003| Security | High     | bcrypt (WF=12)    | Dev/CI           | Code Audit          |
| NFR-004| Quality  | High     | 99.9% Uptime      | Production       | Ping Probes         |
| NFR-005| Scale    | Medium   | Stateless App     | Staging          | Load Balancer Test  |
| NFR-006| Maintain | High     | 0 Ruff/MyPy errors| CI               | Ruff check .        |
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated requirements artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )


class ArchitectureAgentPlugin:
    """Agent that generates feasibility study, system architecture, and tech stack."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.architecture",
            name="Architecture Agent",
            version="0.1.0",
            capabilities=(
                Capability("feasibility-analysis"),
                Capability("architecture-documentation"),
                Capability("technology-stack-recommendation"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        caps = {c.name for c in task.required_capabilities}
        if "feasibility-analysis" in caps:
            name = "04_Feasibility_Study.md"
            meta = get_metadata_header(task.description, "04_Feasibility_Study")
            content = f"""# Feasibility Study

{meta}

## 1. Technical Feasibility
The technical feasibility evaluates whether the system can be built with existing technologies.
- **FastAPI**: A high-performance Python framework utilizing ASGI for asynchronous requests. It
  supports type safety and Pydantic validation out of the box, reducing boilerplate code.
- **PostgreSQL**: A reliable, ACID-compliant relational database. It integrates seamlessly
  with SQLAlchemy for ORM management and Alembic for migrations.
- **Docker**: Provides standardized packaging. Containerization ensures that deployment is
  reproducible across local, staging, and production servers.
The required libraries and infrastructure components are mature, widely documented, and
actively maintained, making the project highly technically feasible.

## 2. Operational Feasibility
Operational feasibility assesses whether the project will be used effectively.
- **Documentation**: Automatic OpenAPI / Swagger docs are generated by FastAPI on `/docs`.
  This simplifies integration for frontend teams and external users.
- **Administration**: PostgreSQL databases are easy to manage using PgAdmin or CLI tools.
- **Deployability**: Simple startup commands (`docker-compose up`) mean operational training
  for deployments is minimal.

## 3. Economic Feasibility
Economic feasibility analyses cost vs. benefit.
- **Software Costs**: All selected technologies (Python, FastAPI, PostgreSQL, Docker) are
  open-source and free to use without licensing fees.
- **Hosting Costs**: The stateless backend application requires minimal hosting resources, and
  can easily run on a low-cost VPS instance.
- **Development Costs**: Python's high readability and rich library ecosystem accelerate
  development speed, reducing overall time-to-market.

## 4. Schedule Feasibility
Schedule feasibility evaluates the timeline.
- **Phase 1 (Setup)**: 1 week for repository and environment initialization.
- **Phase 2 (Auth)**: 1 week for user security and JWT integration.
- **Phase 3 (CRUD)**: 1 week for task logic and database schema design.
- **Phase 4 (Deploy)**: 1 week for container configuration, testing, and release.
Total duration is 4 weeks, which fits standard development cycles.

## 5. Feasibility Scoring Table
Below is the evaluation scoring across key parameters:

| Dimension | Score | Weight | Weighted Score | Rationale |
|-----------|-------|--------|----------------|-----------|
| Tech      | 9.0   | 25%    | 2.25     | Mature toolset |
| Opera     | 8.5   | 20%    | 1.70     | Swagger & docs |
| Econ      | 9.5   | 15%    | 1.425    | Open-source stack |
| Sched     | 8.0   | 15%    | 1.20     | 4-week scope |
| Legal/Sec | 9.0   | 15%    | 1.35     | Standard licenses |
| Resource  | 8.5   | 10%    | 0.85     | 1 developer |
| **Total** | **8.775** | **100%** | **GO** | Highly Feasible |

## 6. Legal & Security Feasibility
- **Licensing**: Open-source licenses (MIT, BSD, Apache 2.0) are respected.
- **Compliance**: User data encryption at rest and hashing in transit protect personal data.
- **Vulnerabilities**: Addressed by regular library dependency scans.

## 7. Resource Feasibility
- **Personnel**: Requires one software developer with intermediate knowledge of Python.
- **Infrastructure**: Standard laptop for development and a single virtual server for deployment.

## 8. Risks and Mitigations
- **Risk**: Database connection failures during high traffic periods.
  - *Mitigation*: Introduce connection pooling and retry logic in SQLAlchemy.
- **Risk**: Unauthorized token manipulation.
  - *Mitigation*: Sign JWT tokens using a strong HMAC SHA-256 algorithm with rotating keys.

## 9. Final Go/No-Go Recommendation
Based on the feasibility scoring of 8.775 / 10, the technical maturity, and zero cost barriers,
the recommendation is a clear **GO**. Proceed to build the system architecture.
"""
        elif "architecture-documentation" in caps:
            name = "05_System_Architecture.md"
            meta = get_metadata_header(task.description, "05_System_Architecture")
            content = f"""# System Architecture

{meta}

## 1. Architectural Overview
This document describes the high-level system architecture of:
"{task.description}".
The system is built on a clean, tiered design pattern to isolate routing, business logic,
and data persistence. High-throughput ASGI processing handles concurrent connections.

## 2. Logical Architecture
The application is structured into the following layers:
- **Presentation Layer (API)**: Exposes endpoints, handles HTTP requests, and validates schemas.
- **Service Layer (Business Logic)**: Coordinates tasks, manages logic, and enforces rules.
- **Data Access Layer (Repository)**: Communicates with PostgreSQL using SQLAlchemy.
- **Infrastructure Layer**: Manages Docker configuration, environment settings, and logs.

## 3. C4-Style System Context Diagram
```mermaid
graph TD
    User[User / Client App] -->|HTTPS Requests| System[AgentForge Task Manager System]
    System -->|Queries/Persists| DB[(PostgreSQL Database System)]
    System -->|Pushes Events| Obs[Observability Event Log]
```

## 4. Container Diagram
```mermaid
graph TD
    User[Client Browser] -->|HTTP / JSON| Frontend[React Single Page Application]
    Frontend -->|OAuth2 / REST API| API[FastAPI Web API Container]
    API -->|TCP / SQL| DB[(PostgreSQL Database Container)]
```

## 5. Component Diagram
```mermaid
graph TD
    Router[FastAPI API Router] -->|Dispatches request| Controller[Authentication/Task Controller]
    Controller -->|Validates payload| Schema[Pydantic Validation Models]
    Controller -->|Delegates logic| Service[Business Logic Service Layer]
    Service -->|Accesses database| Repository[SQLAlchemy Repository Layer]
```

## 6. Deployment Diagram
```mermaid
graph TD
    subgraph Target Host [Linux Virtual Private Server]
        subgraph Docker Compose [Docker Container Network]
            Nginx[Nginx Reverse Proxy Container] -->|Port 8000| API[FastAPI Container]
            API -->|Port 5432| DB[(PostgreSQL Container)]
            DB -->|Persists| Vol[(Docker DB Volume)]
        end
    end
```

## 7. PostgreSQL Schema Design & Database Indexing Notes
The relational schema comprises two principal tables: `users` and `tasks`.

```sql
CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    priority VARCHAR(20) DEFAULT 'medium',
    status VARCHAR(20) DEFAULT 'pending',
    due_date TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
```

### Database Indexing Notes
To optimize query performance:
1. An index on `users(username)` is automatically created via the `UNIQUE` constraint.
2. A foreign key index on `tasks(user_id)` is created to speed up user-specific task fetches.
3. A composite index on `tasks(user_id, status)` is added to optimize task list filtering.

## 8. Architectural Decision Records (ADR)

### ADR-01: FastAPI Framework Selection
- **Status**: Accepted
- **Context**: The application requires highly performant async API processing.
- **Decision**: Selected FastAPI due to Pydantic integration, automatic OpenAPI, and speed.
- **Consequences**: Fast development cycles but requires developer familiarity with ASGI.

### ADR-02: PostgreSQL for Relational Durability
- **Status**: Accepted
- **Context**: Task management demands transactional integrity (ACID) and robust relationships.
- **Decision**: Selected PostgreSQL over MongoDB or SQLite.
- **Consequences**: Guaranteed consistency but requires setting up persistent Docker volumes.

## 9. Security Threat Model Summary
Using the STRIDE framework:
- **Spoofing**: Mitigated by signed JWT tokens and bcrypt password hashing.
- **Tampering**: Mitigated by schema integrity checks and database constraints.
- **Repudiation**: Mitigated by comprehensive transaction and access audit logging.
- **Information Disclosure**: Mitigated by SSL/TLS encryption and redacting hashes from payloads.
- **Denial of Service**: Mitigated by implementing API rate limiting middleware.
"""
        else:
            name = "06_Technology_Stack.md"
            meta = get_metadata_header(task.description, "06_Technology_Stack")
            content = f"""# Technology Stack

{meta}

## 1. Stack Choices and Target Versions
The system relies on the following target component versions:

- **Backend Runtime**: Python `v3.11`
- **API Framework**: FastAPI `v0.110.0`
- **Database Engine**: PostgreSQL `v16.0`
- **Database Driver / ORM**: SQLAlchemy `v2.0.0`
- **Database Migrations**: Alembic `v1.13.0`
- **Testing Engine**: pytest `v8.0.0`
- **Containerization**: Docker `v24.0.0` & Docker Compose `v2.20.0`

## 2. Dependency Categories
- **Direct Dependencies**: FastAPI, SQLAlchemy, Pydantic, PyJWT, passlib, bcrypt.
- **Indirect/Transitive Dependencies**: AnyIO, Starlette, greenlet, typing-extensions.
- **Dev/Testing Dependencies**: pytest, pytest-cov, ruff, mypy, httpx.

## 3. Alternatives Considered and Decision Rationale

| Layer | Chosen | Version | Alternatives | Rationale |
|-------|--------|---------|--------------|-----------|
| API   | FastAPI| 0.110.0 | Flask, Django| Built-in validation |
| DB    | PostgreSQL| 16.0 | MySQL, SQLite| ACID transaction |
| ORM   | SQLAlch.| 2.0.0   | Tortoise ORM | Industry standard |
| Container| Docker| 24.0.0| Podman       | De-facto packaging |
| Test  | pytest | 8.0.0   | unittest     | Simple syntax |

## 4. Stack Maintenance and Security Scanning
To keep the technology stack secure and modern, we will execute automated dependency
vulnerability scanning weekly. Standard tools like `pip-audit` or `safety` will run inside the
CI pipeline to verify no known CVEs exist in installed packages.
Any upgrade of direct dependencies (such as FastAPI or SQLAlchemy) will run through integration
testing to verify no breaking API mutations affect the system stability.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated architecture artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )


class ImplementationAgentPlugin:
    """Agent that generates the implementation plan."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.implementation",
            name="Implementation Agent",
            version="0.1.0",
            capabilities=(Capability("implementation-planning"),),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        meta = get_metadata_header(task.description, "07_Implementation_Plan")
        content = f"""# Implementation Plan

{meta}

## 1. Project Phases

### Phase 1: Environment & Repository Setup
- **Objective**: Establish the boilerplate, directory structure, configurations, and linter gates.
- **Estimated Effort**: 3 Days
- **Deliverables**: Repository scaffold, `pyproject.toml`, Ruff rules, and pre-commit hooks.

### Phase 2: Database Schema & Migration Script Setup
- **Objective**: Define relational models, database connections, and Alembic configuration.
- **Estimated Effort**: 4 Days
- **Deliverables**: SQLAlchemy database models, Alembic environment, migration history scripts.

### Phase 3: Core Security & Auth Endpoints
- **Objective**: Implement user registration, OAuth2 login token endpoint, and JWT authentication.
- **Estimated Effort**: 5 Days
- **Deliverables**: Registration API, login API, and authentication middleware.

### Phase 4: Task CRUD Endpoints Development
- **Objective**: Develop APIs for creating, updating, retrieving, and deleting tasks.
- **Estimated Effort**: 6 Days
- **Deliverables**: `/tasks` endpoints, Pydantic schemas, and sorting/filtering queries.

### Phase 5: Verification & Testing Suite Integration
- **Objective**: Write comprehensive unit tests and integration tests.
- **Estimated Effort**: 4 Days
- **Deliverables**: pytest suite, database mocks, coverage metrics report showing >=90% coverage.

### Phase 6: Docker Containerization & Deployment Orchestration
- **Objective**: Build Dockerfiles and Docker Compose files to launch the application stack.
- **Estimated Effort**: 3 Days
- **Deliverables**: `Dockerfile`, `docker-compose.yml`, local running documentation guide.

## 2. Milestones and Dependencies

- **Milestone 1**: Project repository scaffold initialized (Dependency: None)
- **Milestone 2**: Relational schema successfully applied to Postgres (Dependency: Milestone 1)
- **Milestone 3**: User registration and login flows operational (Dependency: Milestone 2)
- **Milestone 4**: Tasks CRUD APIs fully passing tests (Dependency: Milestone 3)
- **Milestone 5**: Docker Compose environment running successfully (Dependency: Milestone 4)

## 3. Acceptance Criteria per Phase
- **Phase 1**: Ruff linter passes with zero warnings.
- **Phase 2**: Database migrations can be run forwards and backwards successfully.
- **Phase 3**: JWT authorization token verified successfully.
- **Phase 4**: CRUD operations return correct HTTP status codes.
- **Phase 5**: Pytest test suite achieves at least 90% code coverage.
- **Phase 6**: Running `docker-compose up` launches web and database services correctly.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary="Generated implementation plan artifact.",
            artifacts=(Artifact(name="07_Implementation_Plan.md", content=content),),
            confidence=0.9,
        )


class OperationsAgentPlugin:
    """Agent that generates testing strategy, deployment plan, and risk assessment."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.operations",
            name="Operations Agent",
            version="0.1.0",
            capabilities=(
                Capability("testing-strategy"),
                Capability("deployment-planning"),
                Capability("risk-analysis"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        caps = {c.name for c in task.required_capabilities}
        if "testing-strategy" in caps:
            name = "08_Testing_Strategy.md"
            meta = get_metadata_header(task.description, "08_Testing_Strategy")
            content = f"""# Testing Strategy

{meta}

## 1. Test Strategy Overview
This document specifies the testing strategy for the project:
"{task.description}".
To guarantee code quality and prevent regression errors, the project implements a
multi-tiered testing framework encompassing unit tests, integration tests, and API contract
verification tests.

## 2. Testing Levels

### Unit Testing
Unit tests verify the behavior of small modules in isolation. They mock all external
dependencies (like databases or third-party APIs).
- **Tool**: pytest
- **Focus**: Pydantic validations, utility helpers, exception translations.

### Integration Testing
Integration tests verify how modules interact, particularly the interaction between database
services and repository layers.
- **Tool**: pytest with a real temporary PostgreSQL test database.
- **Focus**: Database transactions, relational constraints, ORM mappings.

### API/Contract Testing
API testing checks the correctness of endpoints, security headers, and response formats.
- **Tool**: FastAPI TestClient
- **Focus**: Status codes, JSON payloads, authentication flow.

## 3. Sample Test Cases

### TC-AUTH-001: Register New User
- **Input**:
  `{{"username": "testuser",`
  ` "email": "test@example.com",`
  ` "password": "SecurePassword123"}}`
- **Expected Outcome**: Return HTTP 201 Created with JSON matching the registration model.

### TC-AUTH-002: Login with Incorrect Password
- **Input**:
  `{{"username": "testuser",`
  ` "password": "WrongPassword"}}`
- **Expected Outcome**: Return HTTP 401 Unauthorized with error detail payload.

### TC-TASK-001: Create Task Without Title
- **Input**:
  `{{"description": "This task lacks a title."}}`
- **Expected Outcome**: Return HTTP 422 Unprocessable Entity due to validation error.

## 4. Coverage Targets
The target coverage is set to a minimum of 90% across the codebase.
The continuous integration pipeline will automatically fail if the coverage drops below
this threshold. Code coverage reports are generated automatically using `pytest-cov`.
"""
        elif "deployment-planning" in caps:
            name = "09_Deployment_Plan.md"
            meta = get_metadata_header(task.description, "09_Deployment_Plan")
            content = f"""# Deployment Plan

{meta}

## 1. Deployment Environments

### Local Environment Setup
To run the application locally:
1. Clone the repository and initialize a Python virtual environment.
2. Install dependencies: `pip install -r requirements.txt`.
3. Set environment variables in a local `.env` file.
4. Launch database: `docker-compose up -d db`.
5. Run migrations: `alembic upgrade head`.
6. Start application: `uvicorn src.main:app --reload`.

### Docker Environment Deployment
To build and deploy the entire multi-container stack:
```bash
docker-compose build
docker-compose up -d
```
This command starts both the web API server container and the database server container.

## 2. Environment Variables Configuration
The following variables must be configured in production:
- `DATABASE_URL`: Relational database connection string.
- `SECRET_KEY`: High-entropy key used to sign JWT authorization claims.
- `ALGORITHM`: Set to HS256 for standard JWT signing.
- `ACCESS_TOKEN_EXPIRE_MINUTES`: Expiration time for generated tokens.

## 3. Database Migration Process
Relational schema migrations are managed via Alembic.
- **Generating Migrations**: `alembic revision --autogenerate -m "description"`
- **Applying Migrations**: `alembic upgrade head`
- **Rolling Back Migrations**: `alembic downgrade -1`

## 4. Production Readiness Checklist
- Verify `debug` mode is set to False.
- Change default database credentials to secure passwords.
- Configure resource limits on Docker containers.
- Enforce HTTPS connections only.
- Enable health check endpoint: `/health`.

## 5. Rollback Strategy
If a deployment fails, the following rollback steps must be executed:
1. Revert container image tag to the last known stable build.
2. If schema changes were made, downgrade database using `alembic downgrade`.
3. Restart containers and verify availability via health checks.
"""
        else:
            name = "10_Risk_Assessment.md"
            meta = get_metadata_header(task.description, "10_Risk_Assessment")
            content = f"""# Risk Assessment

{meta}

## 1. Project Risk Management
This document identifies potential security, reliability, and delivery risks for:
"{task.description}".
We establish mitigation actions and contingency plans for all major risks to ensure successful
system development and operations.

## 2. Risk Matrix Table

| Risk ID | Description | Prob. | Impact | Severity | Mitigation | Contingency |
|---------|-------------|-------|--------|----------|------------|-------------|
| RSK-001 | DB Failure  | Low   | Crit   | High     | Pool & retry| Restore backup|
| RSK-002 | SQL Inject  | Low   | Crit   | High     | ORM query  | Key rotation|
| RSK-003 | High Latency| Medium| Medium | Medium   | DB index   | Cache replica|
| RSK-004 | Start Fail  | Medium| High   | High     | CI tests   | Rollback image|
| RSK-005 | Token Leak  | Low   | Crit   | High     | Env secret | Revoke token|

## 3. Security Risk Management
We mandate regular security scans for third-party libraries and code quality tools.
JWT validation secrets must never be committed to source control and must be loaded
from environment variables. Relational databases must reside in private networks.
Furthermore, access logs and database audit logs will be inspected on a weekly basis
to detect unauthorized access patterns or injection attempts early.

## 4. Risk Monitoring and Review
The risk assessment matrix is not a static document. It will be reviewed at the start
of every development sprint. Any new dependencies, infrastructure modifications, or
regulatory compliance shifts will trigger an update to this document.
This keeps our threat model and mitigations fully aligned with the active environment.
We will assign ownership for each risk item to ensure active monitoring.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated operations artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )
