"""Agent plugins for generating professional-grade project planning artifacts.

These agents are domain-context-aware. They read from task.domain_context
and generate highly tailored documents specific to the requested domain.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from agentforge.domain.entities import Artifact, ProjectTask
from agentforge.domain.value_objects import Capability, RiskLevel
from agentforge.runtime.plugins.contracts import (
    AgentExecutionStatus,
    AgentMetadata,
    AgentResult,
)

if TYPE_CHECKING:
    from agentforge.domain_analysis.domain_context import DomainContext


def get_metadata_header(project_name: str, doc_title: str) -> str:
    """Generate a consistent document metadata header."""
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""---
Project Name: {project_name}
Document: {doc_title}
Generated By: AgentForge Orchestrator
Workflow ID: {{{{workflow_id}}}}
Version: 1.0.0
Status: Approved
Last Updated: {now_str}
---"""


def get_resolved_context(task: ProjectTask) -> DomainContext:
    """Retrieve the domain context, falling back to the analyzer if missing."""
    if task.domain_context is not None:
        return task.domain_context

    from agentforge.domain_analysis.domain_analyzer import DomainAnalyzer
    return DomainAnalyzer().analyze(task.description)


class BriefAgentPlugin:
    """Agent that generates the Project Brief artifact."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.brief",
            name="Brief Agent",
            version="0.1.0",
            capabilities=(Capability("project-brief-generation"),),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        ctx = get_resolved_context(task)
        meta = get_metadata_header(ctx.project_name, "01_Project_Brief")

        # Format target users with responsibilities
        target_users_lines = []
        for actor, resp in ctx.actors_with_responsibilities.items():
            target_users_lines.append(f"- **{actor}**: {resp}")
        target_users_str = "\n".join(target_users_lines)

        # Format problems list
        problems_str = "\n".join(f"- {prob}" for prob in ctx.domain_problems)

        # Format goals list
        goals_str = "\n".join(f"- {goal}" for goal in ctx.business_goals)

        # Format success criteria list
        success_str = "\n".join(f"- {crit}" for crit in ctx.measurable_success_criteria)

        # Format modules list
        modules_str = "\n".join(f"- **{mod}**: Coordinates related workflows and data components." for mod in ctx.modules)

        # Format out of scope list
        out_of_scope_str = "\n".join(f"- {item}" for item in ctx.out_of_scope)

        # Format assumptions
        assumptions_str = "\n".join(f"- {item}" for item in ctx.assumptions)

        # Format constraints
        constraints_str = "\n".join(f"- {item}" for item in ctx.constraints)

        content = f"""# Project Brief

{meta}

## 1. Executive Summary
This document serves as the official project brief for the software system:
"{ctx.project_name}".
This initiative will build a robust system tailored for the `{ctx.normalized_domain}` domain. 
Specifically, the system addresses the needs of the `{ctx.institution_context}`.

{ctx.domain_summary}

The implementation focuses on core capabilities such as secure access control, data persistence, and transaction integrity. By providing a clean interface and robust backend services, the application enables users to manage domain operations efficiently while maintaining complete auditability.

## 2. Project Vision
Our vision is to deploy a production-ready `{ctx.project_name}` that transforms operational workflows within the `{ctx.institution_context}`.
The system will replace manual, error-prone record-keeping with automated transactions, ensuring high availability, speed, and reliability. By establishing a centralized repository, the platform provides real-time status visibility, enhances user self-service, and enables managers to make data-driven decisions based on accurate reports.

## 3. Problem Statement
The current operations in the `{ctx.institution_context}` are hindered by key domain challenges:
{problems_str}

These pain points lead to operational delays, security vulnerabilities, data discrepancies, and a lack of reliable audit trails. The system is designed to directly resolve these issues by introducing automated transaction validations and structured datastores.

## 4. Goals and Objectives
The primary business goals for the `{ctx.project_name}` are:
{goals_str}

To achieve these goals, the development team will build a secure API service, implement data integrity constraints at the database level, and automate key business workflows.

## 5. Target Users
The system serves distinct user roles, each with specific responsibilities:
{target_users_str}

By separating roles, the system enforces access security and ensures that users only interact with permitted resources.

## 6. Assumptions and Constraints
### Key Assumptions
{assumptions_str}

### Project Constraints
{constraints_str}

## 7. Scope of Work
The project scope covers the implementation of the following functional areas:
- Design and deployment of the relational database schema.
- Implementation of secure OAuth2 authentication and role-based access control (RBAC).
- Development of core domain modules: {", ".join(ctx.modules)}.
- Automation of business rules and workflow transaction validators.
- Integration of status monitoring, error logs, and automated test coverage.

## 8. Out-of-Scope Items
To keep the initial delivery focused, the following areas are excluded:
{out_of_scope_str}

## 9. High-Level Modules
The application architecture is divided into the following key modules:
{modules_str}

## 10. Success Criteria
The project will be evaluated against the following measurable success criteria:
{success_str}
- Execution of all unit and integration test suites completes with 100% pass rate.
- Successful containerized deployment via Docker Compose.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated project brief artifact for {ctx.project_name}.",
            artifacts=(Artifact(name="01_Project_Brief.md", content=content),),
            confidence=0.9,
        )


class RequirementsAgentPlugin:
    """Agent that generates functional and non-functional requirements."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.requirements",
            name="Requirements Agent",
            version="0.1.0",
            capabilities=(
                Capability("requirements-analysis"),
                Capability("non-functional-requirements-analysis"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        ctx = get_resolved_context(task)
        caps = {c.name for c in task.required_capabilities}

        if "requirements-analysis" in caps:
            name = "02_Functional_Requirements.md"
            meta = get_metadata_header(ctx.project_name, "02_Functional_Requirements")

            # API Resource specifications
            api_lines = []
            for api in ctx.api_resources:
                if "auth" in api or "token" in api:
                    method = "POST"
                    desc = "Authenticate user or request OAuth2 session token"
                    auth = "No"
                elif "register" in api:
                    method = "POST"
                    desc = "Register a new user account"
                    auth = "No"
                elif "catalog" in api or "search" in api:
                    method = "GET"
                    desc = "Browse and search catalog resources"
                    auth = "No/Yes"
                else:
                    method = "POST/GET/PUT"
                    desc = f"Manage {api.split('/')[-1]} resources"
                    auth = "Yes"
                api_lines.append(f"| {method} | `{api}` | {desc} | {auth} |")
            api_table = "\n".join(api_lines)

            # Bullet lists
            actors_bullet = "\n".join(f"- **{actor}**: Has designated access levels for domain actions." for actor in ctx.actors)
            entities_bullet = "\n".join(f"- **{entity}**: Core domain model tracked in database." for entity in ctx.entities)
            br_bullet = "\n".join(f"- **BR-{i+1:03d}**: {rule}" for i, rule in enumerate(ctx.business_rules))
            val_bullet = "\n".join(f"- {rule}" for rule in ctx.validation_rules)
            ec_bullet = "\n".join(f"- {case}" for case in ctx.edge_cases)

            # Detailed functional requirements specifications
            fr_specs_lines = []
            for req in ctx.functional_requirements:
                parts = req.split(" ", 1)
                req_id = parts[0]
                req_title = parts[1] if len(parts) > 1 else req
                
                # Determine relevant actors for this FR
                relevant_actors = []
                req_title_lower = req_title.lower()
                for actor in ctx.actors:
                    actor_lower = actor.lower()
                    # Check if actor is likely responsible
                    if "student" in actor_lower or "faculty" in actor_lower:
                        if any(w in req_title_lower for w in ["search", "filter", "reserve", "register", "profile"]):
                            relevant_actors.append(actor)
                    elif "librarian" in actor_lower or "merchant" in actor_lower or "manager" in actor_lower or "doctor" in actor_lower or "staff" in actor_lower:
                        if not any(w in req_title_lower for w in ["student", "faculty"]):
                            relevant_actors.append(actor)
                    elif "admin" in actor_lower:
                        relevant_actors.append(actor)
                if not relevant_actors:
                    relevant_actors = list(ctx.actors)

                fr_specs_lines.append(f"""### {req_id}: {req_title}
- **Description**: The system must provide robust capability to support {req_title_lower} operations.
- **Actors**: {", ".join(relevant_actors)}
- **Preconditions**:
  1. The user is logged in with an active session token.
  2. The database connection is active and relational tables exist.
- **Main Flow**:
  1. The user initiates the {req_title_lower} action.
  2. The system checks role-based access permissions.
  3. The system validates input values against business rules.
  4. The system executes the transaction and updates relational states.
  5. The system saves audit details and returns a successful response.
- **Acceptance Criteria**:
  - The transaction executes atomically under 200ms.
  - The correct data changes are persisted in the database.
  - Validation failures return clear HTTP error responses.
- **Error Cases**:
  - **ERR-001**: Role-based access denied. Action is aborted, returns HTTP 403.
  - **ERR-002**: Validation failed. Inputs do not match constraints, returns HTTP 422.
  - **ERR-003**: Resource conflict. Target database records are locked or unavailable, returns HTTP 409.""")
            fr_specs_str = "\n\n".join(fr_specs_lines)

            content = f"""# Functional Requirements

{meta}

## 1. Document Purpose
This document specifies the complete functional requirements for the software system:
"{ctx.project_name}".
It establishes the baseline for development, testing, and eventual system acceptance.

## 2. System Overview
The system provides a capability-driven backend service implementing core `{ctx.project_name}` workflows. Key capabilities include secure role-based access, relational persistence, domain entity operations, and validation.
The application utilizes clean architecture to separate the business logic from infrastructure concerns. By decoupling the interfaces, domain models, and storage adapters, the system remains maintainable.

### Core Entities
The primary domain entities managed by the system are:
{entities_bullet}

## 3. Actors and Users
A clear definition of actors establishes the user boundary of the system:
{actors_bullet}

## 4. Authorization Matrix
The following matrix defines resource access permissions:

{ctx.authorization_matrix}

## 5. API Endpoint Specifications
The backend service exposes the following endpoints:

| Method | Endpoint | Description | Auth Required |
|--------|----------|-------------|---------------|
{api_table}

## 6. Request and Response Examples
These integration contract examples illustrate the expected request body structures and successful responses:

{ctx.request_response_examples}

## 7. Functional Requirements Details
Below are the detailed specifications for each functional requirement:

{fr_specs_str}

## 8. Business and Validation Rules
The system enforces the following domain rules and constraints:
{br_bullet}

### Data Validation Rules
{val_bullet}

## 9. Edge Cases and Handling
{ec_bullet}

## 10. Traceability Matrix
This matrix maps functional requirements to verification methods and components:

{ctx.traceability_matrix}
"""
        else:
            name = "03_Non_Functional_Requirements.md"
            meta = get_metadata_header(ctx.project_name, "03_Non_Functional_Requirements")

            # Non-Functional Requirements details
            nfr_specs = []
            nfr_matrix_lines = []
            for i, nfr in enumerate(ctx.non_functional_requirements):
                nfr_id = f"NFR-{i+1:03d}"
                cat = "Performance" if "latency" in nfr.lower() or "speed" in nfr.lower() else "Security" if "access" in nfr.lower() or "privacy" in nfr.lower() else "Reliability"
                
                nfr_specs.append(f"""### {nfr_id}: {nfr}
- **Category**: {cat}
- **Description**: {nfr}
- **Success Threshold**: The system meets this target consistently under ordinary workloads.
- **Failure Threshold**: Operations fall outside parameters, triggering automated warnings.
- **Verification Environment**: Dedicated Staging environment mimicking production configurations.
- **Monitoring Signal**: Automated Prometheus metrics, performance logs, and audit trail records.""")
                
                # Make sure there is NO TRUNCATION (...) in the matrix table
                nfr_matrix_lines.append(f"| {nfr_id} | {cat} | High | Matches the {nfr.lower()} targets | Staging | Automated performance and audit verification tests |")
            
            nfr_specs_str = "\n\n".join(nfr_specs)
            nfr_matrix_str = "\n".join(nfr_matrix_lines)

            content = f"""# Non-Functional Requirements

{meta}

## 1. Measurable NFR Specifications

{nfr_specs_str}

## 2. NFR Verification Matrix

| NFR ID | Category | Priority | Success Threshold | Verification Env | Verification Method |
|--------|----------|----------|-------------------|------------------|---------------------|
{nfr_matrix_str}
"""

        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated requirements artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )


class ArchitectureAgentPlugin:
    """Agent that generates feasibility study, system architecture, and tech stack."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.architecture",
            name="Architecture Agent",
            version="0.1.0",
            capabilities=(
                Capability("feasibility-analysis"),
                Capability("architecture-documentation"),
                Capability("technology-stack-recommendation"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        ctx = get_resolved_context(task)
        caps = {c.name for c in task.required_capabilities}

        if "feasibility-analysis" in caps:
            name = "04_Feasibility_Study.md"
            meta = get_metadata_header(ctx.project_name, "04_Feasibility_Study")

            tech_details = ctx.feasibility_points.get("technical", "Technical feasibility is high due to standard software stacks.")
            oper_details = ctx.feasibility_points.get("operational", "Operational workflow fits within standard administrative routines.")
            econ_details = ctx.feasibility_points.get("economic", "Economic feasibility is high since the project uses open-source packages.")
            sched_details = ctx.feasibility_points.get("schedule", "Timeline fits standard phases.")
            legal_details = ctx.feasibility_points.get("legal", "No significant legal barriers exist.")

            # Risks list
            risks_lines = []
            for i, risk in enumerate(ctx.risks):
                risks_lines.append(f"- **Risk {i+1}**: {risk}\n  - *Mitigation*: Implementation of proper validators, transaction locks, and access controls.")
            risks_str = "\n".join(risks_lines)

            content = f"""# Feasibility Study

{meta}

## 1. Technical Feasibility
The technical feasibility evaluates whether the system can be built with existing technologies.
- **Database Indexing**: Relational database indexes optimize queries and ensure fast lookup.
- **Concurrency & Transactions**: ACID transactions protect entity states and prevent concurrent data conflicts.
- **Feasibility Details**: {tech_details}

## 2. Operational Feasibility
Operational feasibility assesses whether the project will be used effectively.
- **Self-Service Portals**: Portals improve the user workflow by allowing direct actions (e.g. catalog searches, reservations).
- **Administration**: Administrators can update policies and review logs easily.
- **Feasibility Details**: {oper_details}

## 3. Economic Feasibility
Economic feasibility analyses cost vs. benefit.
- **Cost Reduction**: Replaces manual paper ledgers with automated, error-free systems, reducing physical losses.
- **Software Costs**: Built with open-source technologies (Python, FastAPI, PostgreSQL, Docker).
- **Feasibility Details**: {econ_details}

## 4. Schedule Feasibility
Schedule feasibility evaluates the timeline based on core modules.
The project requires building the following modules: {", ".join(ctx.modules)}.
- **Feasibility Details**: {sched_details}

## 5. Feasibility Scoring Table
Below is the evaluation scoring across key parameters:

| Dimension | Score | Weight | Weighted Score | Rationale |
|-----------|-------|--------|----------------|-----------|
| Tech      | 9.0   | 25%    | 2.25           | Standard tools & databases |
| Opera     | 8.5   | 20%    | 1.70           | Clean Swagger API & self-service |
| Econ      | 9.5   | 15%    | 1.425          | Open-source stack, no licensing fees |
| Sched     | 8.0   | 15%    | 1.20           | Phased timeline is practical |
| Legal/Sec | 9.0   | 15%    | 1.35           | Access logging & encryption |
| Resource  | 8.5   | 10%    | 0.85           | Fits 1 developer workload |
| **Total** | **8.775** | **100%** | **GO**   | Highly Feasible |

## 6. Legal & Security Feasibility
- **Privacy Compliance**: All user records are protected and access history is tracked.
- **Audit Trails**: Security policies enforce audit trail logging.
- **Feasibility Details**: {legal_details}

## 7. Resource Feasibility
- **Personnel**: Fits a single developer with standard Python and database skills.
- **Infrastructure**: Standard container environment running on host virtual machines.

## 8. Risks and Mitigations
{risks_str}

## 9. Final Go/No-Go Recommendation
Based on the feasibility scoring of 8.775 / 10 and technical maturity, the recommendation is a clear **GO**.
"""
        elif "architecture-documentation" in caps:
            name = "05_System_Architecture.md"
            meta = get_metadata_header(ctx.project_name, "05_System_Architecture")

            # Dynamic component services
            services_lines = []
            for mod in ctx.modules:
                service_name = mod.replace(" Management", "").replace(" and Role", "").replace(" and Analytics", "").strip()
                service_name = service_name.replace(" ", "")
                services_lines.append(f"    API -->|delegates to| {service_name}Service[{service_name} Service]")
            services_str = "\n".join(services_lines)

            # Dynamic SQL DDL generation
            ddl_lines = []
            for table in ctx.database_tables:
                ddl_lines.append(get_table_ddl(table))
            ddl_str = "\n\n".join(ddl_lines)

            content = f"""# System Architecture

{meta}

## 1. Architectural Overview
This document describes the high-level system architecture of:
"{ctx.project_name}".
The system is built on a clean, tiered design pattern to isolate routing, business logic, and data persistence. High-throughput ASGI processing handles concurrent connections.

## 2. Logical Architecture
The application is structured into the following layers:
- **Presentation Layer (API)**: Exposes endpoints, handles HTTP requests, and validates schemas.
- **Service Layer (Business Logic)**: Coordinates tasks, manages logic, and enforces rules.
- **Data Access Layer (Repository)**: Communicates with database using SQLAlchemy.
- **Infrastructure Layer**: Manages Docker configuration, environment settings, and logs.

## 3. C4-Style System Context Diagram
```mermaid
graph TD
    User[User / Client App] -->|HTTPS Requests| System[{ctx.project_name} System]
    System -->|Queries/Persists| DB[(PostgreSQL Database System)]
    System -->|Pushes Events| Obs[Observability Event Log]
```

## 4. Container Diagram
```mermaid
graph TD
    User[Client Browser] -->|HTTP / JSON| Frontend[React Single Page Application]
    Frontend -->|OAuth2 / REST API| API[FastAPI Web API Container]
    API -->|TCP / SQL| DB[(PostgreSQL Database Container)]
```

## 5. Component Diagram
```mermaid
graph TD
    Router[FastAPI API Router] -->|Dispatches request| Controller[API Router Controller]
    Controller -->|Validates payload| Schema[Pydantic Validation Models]
{services_str}
```

## 6. Deployment Diagram
```mermaid
graph TD
    subgraph Target Host [{ctx.institution_context}]
        subgraph Docker Compose [Docker Container Network]
            Nginx[Nginx Reverse Proxy Container] -->|Port 8000| API[FastAPI Container]
            API -->|Port 5432| DB[(PostgreSQL Database Container)]
            DB -->|Persists| Vol[(Docker DB Volume)]
        end
    end
```

## 7. PostgreSQL Schema Design & Database Indexing Notes
The database schema consists of the following relational tables:

```sql
{ddl_str}
```

### Database Indexing Notes
To optimize query performance:
1. Index foreign key columns to speed up relational fetches.
2. Composite index on status columns to speed up list filtering.

## 8. Architectural Decision Records (ADR)

### ADR-01: FastAPI Framework Selection
- **Status**: Accepted
- **Context**: The application requires highly performant async API processing.
- **Decision**: Selected FastAPI due to Pydantic integration, automatic OpenAPI, and speed.

### ADR-02: PostgreSQL for Relational Durability
- **Status**: Accepted
- **Context**: Relational data integrity is critical for transactions.
- **Decision**: Selected PostgreSQL to guarantee consistency.

## 9. Security Threat Model Summary
To ensure the system's resilience, we model key threats and mitigations:
- **STRIDE-1 (Spoofing)**: Mitigated by requiring secure JWT signatures and validating user session keys.
- **STRIDE-2 (Tampering)**: Mitigated by database constraints and transport layer encryption.
- **STRIDE-3 (Information Disclosure)**: Mitigated by encrypted database connections and CORS headers.
"""
        else:
            name = "06_Technology_Stack.md"
            meta = get_metadata_header(ctx.project_name, "06_Technology_Stack")

            # Stack justification
            justification = get_stack_rationale(ctx.normalized_domain)

            content = f"""# Technology Stack

{meta}

## 1. Stack Choices and Target Versions
The system relies on the following target component versions:

- **Backend Runtime**: Python `v3.11` (Selected for modern language features, performance improvements, and stable library compatibility).
- **API Framework**: FastAPI `v0.110.0` (Asynchronous performance, instant OpenAPI generation, and native type hint checking).
- **Database Engine**: PostgreSQL `v16.0` (Robust, enterprise-grade relational database guaranteeing transactional ACID properties).
- **Database Driver / ORM**: SQLAlchemy `v2.0.0` (Unified model syntax, robust connection pooling, and declarative mappings).
- **Database Migrations**: Alembic `v1.13.0` (Clean schema evolution versioning, automatic generation scripts, and rollback support).
- **Testing Engine**: pytest `v8.0.0` (Lightweight testing, clean fixture inheritance, and extensive plugin support).
- **Containerization**: Docker `v24.0.0` & Docker Compose `v2.20.0` (Guaranteed reproducibility across environments).

## 2. Dependency Categories

### Direct Production Dependencies
- **FastAPI**: Main routing and controller entrypoints handler.
- **SQLAlchemy**: The Object Relational Mapper used to communicate securely with PostgreSQL.
- **Pydantic**: Data schema parsing and request payload validation.
- **PyJWT**: Secure creation and validation of cryptographic user login tokens.
- **Passlib & Bcrypt**: One-way salting and hashing of sensitive user passwords.

### Development and Test Dependencies
- **pytest & httpx**: Integration testing of REST endpoints and database behaviors.
- **pytest-cov**: Verifying that total code test coverage stays above the mandatory 90% threshold.
- **Ruff**: Modern, ultra-fast Python linter and formatter to keep code clean and uniform.
- **MyPy**: Static type checker to catch potential type errors prior to execution.

## 3. Rationale for Stack Choices
{justification}
This collection of technologies forms an industry-standard modern stack for enterprise APIs. The components are chosen for their high performance, strong type-safety features, active community support, and ease of deployment.

## 4. Stack Maintenance and Security Scanning
To keep the technology stack secure and modern, we will execute automated dependency
vulnerability scanning weekly. Standard tools like `pip-audit` or `safety` will run inside the
CI pipeline to verify no known CVEs exist in installed packages.
Additionally, dependabot or similar automated dependency update tools will be configured to regularly check for security patches.

## 5. Alternatives Considered and Decision Rationale
- **Alternative 1: Django/Flask**: Discarded due to lack of native async support, heavy default footprint (Django), or manual validation wiring (Flask).
- **Alternative 2: SQLite**: Discarded as it is not suited for high concurrency or distributed multi-replica container environments.
- **Alternative 3: MongoDB**: Discarded since relational integrity, strict foreign key constraints, and join logic are required.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated architecture artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )


class ImplementationAgentPlugin:
    """Agent that generates the implementation plan."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.implementation",
            name="Implementation Agent",
            version="0.1.0",
            capabilities=(Capability("implementation-planning"),),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        ctx = get_resolved_context(task)
        meta = get_metadata_header(ctx.project_name, "07_Implementation_Plan")

        # Dynamic phases based on modules
        phases_lines = [
            "### Phase 1: Environment & Repository Setup\n- **Objective**: Establish the boilerplate, directory structure, configurations, and linter gates.\n- **Estimated Effort**: 3 Days\n- **Deliverables**: Repository scaffold, `pyproject.toml`, Ruff rules.",
            "### Phase 2: User Authentication & Role-Based Access (RBAC)\n- **Objective**: Implement user registration, OAuth2 login token endpoint, and JWT authentication.\n- **Estimated Effort**: 4 Days\n- **Deliverables**: Registration API, login API, authentication middleware."
        ]
        for i, mod in enumerate(ctx.modules):
            phases_lines.append(f"### Phase {i+3}: {mod} Implementation\n- **Objective**: Implement backend services, models, and endpoints for {mod.lower()}.\n- **Estimated Effort**: 5 Days\n- **Deliverables**: Core API endpoints, migrations, and Pydantic schemas for {mod}.")
        
        qa_index = len(ctx.modules) + 3
        deploy_index = len(ctx.modules) + 4
        phases_lines.append(f"### Phase {qa_index}: Integration Testing & QA\n- **Objective**: Write comprehensive unit tests and integration tests.\n- **Estimated Effort**: 4 Days\n- **Deliverables**: pytest suite with 90% code coverage.")
        phases_lines.append(f"### Phase {deploy_index}: Containerization & Deployment Orchestration\n- **Objective**: Build Dockerfiles and Compose configs to launch the application stack.\n- **Estimated Effort**: 3 Days\n- **Deliverables**: `Dockerfile`, `docker-compose.yml`.")

        phases_str = "\n\n".join(phases_lines)

        content = f"""# Implementation Plan

{meta}

## 1. Project Phases

{phases_str}

## 2. Milestones and Dependencies

- **Milestone 1**: Project repository scaffold initialized (Dependency: None)
- **Milestone 2**: Relational schema successfully applied to Postgres (Dependency: Milestone 1)
- **Milestone 3**: User registration and login flows operational (Dependency: Milestone 2)
- **Milestone 4**: Core domain APIs fully passing tests (Dependency: Milestone 3)
- **Milestone 5**: Docker Compose environment running successfully (Dependency: Milestone 4)

## 3. Acceptance Criteria per Phase
- **Phase 1**: Ruff linter passes with zero warnings.
- **Phase 2**: Database migrations can be run forwards and backwards successfully.
- **Phase 3**: JWT authorization token verified successfully.
- **Phase 4**: CRUD operations return correct HTTP status codes.
"""
        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated implementation plan artifact for {ctx.project_name}.",
            artifacts=(Artifact(name="07_Implementation_Plan.md", content=content),),
            confidence=0.9,
        )


class OperationsAgentPlugin:
    """Agent that generates testing strategy, deployment plan, and risk assessment."""

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            agent_id="builtin.operations",
            name="Operations Agent",
            version="0.1.0",
            capabilities=(
                Capability("testing-strategy"),
                Capability("deployment-planning"),
                Capability("risk-analysis"),
            ),
            required_tools=(),
            risk_level=RiskLevel.LOW,
        )

    def execute(self, task: ProjectTask) -> AgentResult:
        ctx = get_resolved_context(task)
        caps = {c.name for c in task.required_capabilities}

        if "testing-strategy" in caps:
            name = "08_Testing_Strategy.md"
            meta = get_metadata_header(ctx.project_name, "08_Testing_Strategy")

            # Dynamic test cases
            test_cases_str = get_test_cases(ctx.normalized_domain)

            content = f"""# Testing Strategy

{meta}

## 1. Test Strategy Overview
This document specifies the testing strategy for the project:
"{ctx.project_name}".
To guarantee code quality and prevent regression errors, the project implements a
multi-tiered testing framework encompassing unit tests, integration tests, and API contract
verification tests.

## 2. Testing Levels

### Unit Testing
Unit tests verify the behavior of small modules in isolation. They mock all external
dependencies (like databases or third-party APIs).
- **Tool**: pytest
- **Focus**: Pydantic validations, utility helpers, exception translations.

### Integration Testing
Integration tests verify how modules interact, particularly the interaction between database
services and repository layers.
- **Tool**: pytest with a real temporary PostgreSQL test database.
- **Focus**: Database transactions, relational constraints, ORM mappings.

### API/Contract Testing
API testing checks the correctness of endpoints, security headers, and response formats.
- **Tool**: FastAPI TestClient
- **Focus**: Status codes, JSON payloads, authentication flow.

## 3. Sample Test Cases

{test_cases_str}

## 4. Coverage Targets
The target coverage is set to a minimum of 90% across the codebase.
The continuous integration pipeline will automatically fail if the coverage drops below
this threshold. Code coverage reports are generated automatically using `pytest-cov`.
"""
        elif "deployment-planning" in caps:
            name = "09_Deployment_Plan.md"
            meta = get_metadata_header(ctx.project_name, "09_Deployment_Plan")

            content = f"""# Deployment Plan

{meta}

## 1. Deployment Environments
The system is targeted for deployment in the `{ctx.institution_context}`.
The environment setup supports development, staging, and stable production nodes.

### Local Environment Setup
To run the application locally:
1. Clone the repository and initialize a Python virtual environment.
2. Install dependencies: `pip install -e .`.
3. Set environment variables in a local `.env` file.
4. Launch database: `docker-compose up -d db`.
5. Run migrations: `alembic upgrade head`.
6. Start application: `uvicorn src.main:app --reload`.

### Docker Environment Deployment
To build and deploy the entire multi-container stack:
```bash
docker-compose build
docker-compose up -d
```
This command starts both the web API server container and the database server container.

## 2. Environment Variables Configuration
The following variables must be configured in production:
- `DATABASE_URL`: Relational database connection string.
- `SECRET_KEY`: High-entropy key used to sign JWT authorization claims.
- `ALGORITHM`: Set to HS256 for standard JWT signing.

## 3. Database Migration Process
Relational schema migrations are managed via Alembic.
- **Generating Migrations**: `alembic revision --autogenerate -m "description"`
- **Applying Migrations**: `alembic upgrade head`
- **Rolling Back Migrations**: `alembic downgrade -1`

## 4. Production Readiness Checklist
- Verify `debug` mode is set to False.
- Change default database credentials to secure passwords.
- Configure resource limits on Docker containers.
- Enforce HTTPS connections only.
- Enable health check endpoint: `/health`.

## 5. Rollback Strategy
If a deployment fails, the following rollback steps must be executed:
1. Revert container image tag to the last known stable build.
2. If schema changes were made, downgrade database using `alembic downgrade`.
3. Restart containers and verify availability via health checks.
"""
        else:
            name = "10_Risk_Assessment.md"
            meta = get_metadata_header(ctx.project_name, "10_Risk_Assessment")

            # Dynamic risk matrix
            risk_lines = []
            for i, risk in enumerate(ctx.risks):
                severity = "High" if i % 2 == 0 else "Medium"
                impact = "Crit" if i % 2 == 0 else "Medium"
                prob = "Low" if i % 2 == 0 else "Medium"
                risk_lines.append(f"| RSK-{i+1:03d} | {risk} | {prob} | {impact} | {severity} | Input validation / Constraints | Audit trail review |")
            risk_table = "\n".join(risk_lines)

            content = f"""# Risk Assessment

{meta}

## 1. Project Risk Management
This document identifies potential security, reliability, and delivery risks for:
"{ctx.project_name}".
We establish mitigation actions and contingency plans for all major risks to ensure successful
system development and operations.

## 2. Risk Matrix Table

| Risk ID | Description | Prob. | Impact | Severity | Mitigation | Contingency |
|---------|-------------|-------|--------|----------|------------|-------------|
{risk_table}

## 3. Security Risk Management
We mandate regular security scans for third-party libraries and code quality tools.
JWT validation secrets must never be committed to source control and must be loaded
from environment variables. Relational databases must reside in private networks.
Furthermore, access logs and database audit logs will be inspected on a weekly basis
to detect unauthorized access patterns or injection attempts early.

## 4. Risk Monitoring and Review
The risk assessment matrix is not a static document. It will be reviewed at the start
of every development sprint. Any new dependencies, infrastructure modifications, or
regulatory compliance shifts will trigger an update to this document.
This keeps our threat model and mitigations fully aligned with the active environment.
We will assign ownership for each risk item to ensure active monitoring.
"""

        return AgentResult(
            status=AgentExecutionStatus.SUCCESS,
            summary=f"Generated operations/requirements artifact: {name}.",
            artifacts=(Artifact(name=name, content=content),),
            confidence=0.9,
        )


# ---------------------------------------------------------------------------
# Helper functions for dynamic document sections
# ---------------------------------------------------------------------------

def get_table_ddl(table: str) -> str:
    """Return DDL definition for a given database table name."""
    fields = {
        "users": "    id UUID PRIMARY KEY,\n    username VARCHAR(50) UNIQUE NOT NULL,\n    email VARCHAR(100) UNIQUE NOT NULL,\n    hashed_password VARCHAR(255) NOT NULL",
        "roles": "    id UUID PRIMARY KEY,\n    name VARCHAR(30) UNIQUE NOT NULL",
        "members": "    id UUID PRIMARY KEY,\n    user_id UUID REFERENCES users(id),\n    borrowing_limit INTEGER DEFAULT 5",
        "books": "    id UUID PRIMARY KEY,\n    isbn VARCHAR(20) UNIQUE NOT NULL,\n    title VARCHAR(100) NOT NULL,\n    author VARCHAR(100) NOT NULL",
        "book_copies": "    id UUID PRIMARY KEY,\n    book_id UUID REFERENCES books(id),\n    status VARCHAR(20) DEFAULT 'available'",
        "loans": "    id UUID PRIMARY KEY,\n    member_id UUID REFERENCES members(id),\n    book_copy_id UUID REFERENCES book_copies(id),\n    due_date TIMESTAMP WITH TIME ZONE,\n    status VARCHAR(20) DEFAULT 'issued'",
        "reservations": "    id UUID PRIMARY KEY,\n    member_id UUID REFERENCES members(id),\n    book_id UUID REFERENCES books(id),\n    status VARCHAR(20) DEFAULT 'pending'",
        "fines": "    id UUID PRIMARY KEY,\n    loan_id UUID REFERENCES loans(id),\n    amount DECIMAL(10,2) NOT NULL,\n    status VARCHAR(20) DEFAULT 'unpaid'",
        "products": "    id UUID PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    price DECIMAL(10,2) NOT NULL,\n    stock INTEGER DEFAULT 0",
        "orders": "    id UUID PRIMARY KEY,\n    user_id UUID REFERENCES users(id),\n    total DECIMAL(10,2) NOT NULL,\n    status VARCHAR(20) DEFAULT 'pending'",
        "order_items": "    id UUID PRIMARY KEY,\n    order_id UUID REFERENCES orders(id),\n    product_id UUID REFERENCES products(id),\n    quantity INTEGER NOT NULL",
        "payments": "    id UUID PRIMARY KEY,\n    order_id UUID REFERENCES orders(id),\n    amount DECIMAL(10,2) NOT NULL,\n    status VARCHAR(20) DEFAULT 'completed'",
        "courses": "    id UUID PRIMARY KEY,\n    title VARCHAR(100) NOT NULL,\n    instructor_id UUID REFERENCES users(id)",
        "lessons": "    id UUID PRIMARY KEY,\n    course_id UUID REFERENCES courses(id),\n    title VARCHAR(100) NOT NULL",
        "quizzes": "    id UUID PRIMARY KEY,\n    lesson_id UUID REFERENCES lessons(id),\n    max_score INTEGER DEFAULT 100",
        "enrollments": "    id UUID PRIMARY KEY,\n    student_id UUID REFERENCES users(id),\n    course_id UUID REFERENCES courses(id)",
        "patients": "    id UUID PRIMARY KEY,\n    user_id UUID REFERENCES users(id),\n    date_of_birth DATE NOT NULL",
        "appointments": "    id UUID PRIMARY KEY,\n    patient_id UUID REFERENCES patients(id),\n    doctor_id UUID REFERENCES users(id),\n    appointment_time TIMESTAMP WITH TIME ZONE",
        "prescriptions": "    id UUID PRIMARY KEY,\n    appointment_id UUID REFERENCES appointments(id),\n    medication VARCHAR(100) NOT NULL,\n    dosage VARCHAR(50) NOT NULL",
        "inventory_items": "    id UUID PRIMARY KEY,\n    sku VARCHAR(50) UNIQUE NOT NULL,\n    quantity INTEGER DEFAULT 0",
        "warehouses": "    id UUID PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    location VARCHAR(255)",
        "purchase_orders": "    id UUID PRIMARY KEY,\n    supplier_id UUID REFERENCES suppliers(id),\n    total DECIMAL(10,2) NOT NULL",
        "suppliers": "    id UUID PRIMARY KEY,\n    name VARCHAR(100) NOT NULL,\n    email VARCHAR(100)",
        "library_policies": "    id UUID PRIMARY KEY,\n    policy_name VARCHAR(100) UNIQUE NOT NULL,\n    value VARCHAR(255) NOT NULL",
        "audit_logs": "    id UUID PRIMARY KEY,\n    user_id UUID REFERENCES users(id),\n    action VARCHAR(255) NOT NULL,\n    details TEXT",
    }
    f_str = fields.get(table, "    id UUID PRIMARY KEY,\n    name VARCHAR(100) NOT NULL")
    return f"CREATE TABLE {table} (\n{f_str},\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP\n);"


def get_stack_rationale(domain: str) -> str:
    """Return domain stack rationale justification."""
    if domain == "library-management":
        return "FastAPI provides instant OpenAPI documentation, making it easy to build Catalog search endpoints. PostgreSQL ensures ACID transactions for book copy checkout (loans) and reservation status updates, preventing double issuing of the same physical copy."
    if domain == "ecommerce":
        return "FastAPI uses modern ASGI concurrency to support thousands of customers browsing and checking out simultaneously. PostgreSQL handles critical payment and order state transaction safety with high integrity."
    if domain == "hospital-management":
        return "FastAPI supports secure token authentication for patient record endpoints. PostgreSQL supports relational schema complexity for patient histories, appointments, and bills, with encryption compatibility for HIPAA compliance."
    return "FastAPI is lightweight with high performance for web APIs. PostgreSQL is a mature relational database ensuring ACID transactional safety and relational durability."


def get_test_cases(domain: str) -> str:
    """Return tailored test cases for the domain."""
    if domain == "library-management":
        return """### TC-CIRC-001: Librarian can issue available book copy
- **Input**: `{ "member_id": "member-uuid", "book_copy_id": "copy-uuid" }`
- **Expected Outcome**: Return HTTP 201 Created. Loan status set to issued.

### TC-CIRC-002: Unavailable book copy cannot be issued
- **Input**: `{ "member_id": "member-uuid", "book_copy_id": "copy-uuid-already-loaned" }`
- **Expected Outcome**: Return HTTP 400 Bad Request due to copy status conflict.

### TC-FINE-001: Overdue fine is calculated correctly
- **Input**: Trigger daily fine calculation routine for overdue loan record.
- **Expected Outcome**: Overdue fine record generated matching configured rate * days.

### TC-RES-001: Reserved book copy cannot be issued to other members
- **Input**: Member B tries to borrow copy currently reserved by Member A.
- **Expected Outcome**: Return HTTP 403 Forbidden due to reservation conflict.

### TC-MEMB-001: Student can search catalog
- **Input**: Query catalog by title or ISBN.
- **Expected Outcome**: Return list of matching books with availability status.

### TC-CIRC-003: Student cannot issue a book directly without librarian approval
- **Input**: Student tries to POST loan directly.
- **Expected Outcome**: Return HTTP 403 Forbidden.

### TC-REP-001: Admin can generate reports
- **Input**: Request overdue and inventory report compilation.
- **Expected Outcome**: Return formatted reports successfully."""
    
    if domain == "ecommerce":
        return """### TC-ORD-001: Customer checkout creates order
- **Input**: `{ "cart_id": "cart-uuid" }`
- **Expected Outcome**: Order created, stock reserved, transaction marked pending payment.

### TC-PAY-001: Payment transaction processing
- **Input**: Pay for order using payment gateway payload.
- **Expected Outcome**: Status set to paid, invoice issued.

### TC-INV-001: Restock trigger on low stock
- **Input**: Reduce inventory below minimum threshold.
- **Expected Outcome**: System triggers inventory alert email."""
        
    return """### TC-AUTH-001: Register New User
- **Input**: User registration parameters.
- **Expected Outcome**: Return HTTP 201 Created.

### TC-AUTH-002: Login with Incorrect Password
- **Input**: Bad password payload.
- **Expected Outcome**: Return HTTP 401 Unauthorized."""
