"""New domain packs for AgentForge.

Provides registry entries for school, gym, hostel, car rental, and blood donation domains.
"""

from __future__ import annotations

from agentforge.domain_analysis.domain_context import DomainContext

NEW_PACKS: dict[str, DomainContext] = {
    "school-management": DomainContext(
        project_name="School Management System",
        normalized_domain="school-management",
        domain_type="School Management",
        domain_summary=(
            "The School Management System coordinates student admissions, class and section allocations, "
            "attendance tracking, exams, marks entry, and report card generation."
        ),
        institution_context="K-12 School Administration Environment",
        primary_users=["Student", "Teacher", "Parent"],
        secondary_users=["School Administrator", "Accountant", "Principal"],
        actors=["Student", "Teacher", "Parent", "School Administrator", "Accountant", "Principal"],
        actors_with_responsibilities={
            "Student": "view class timetable, download assignments, view exam marks and report cards.",
            "Teacher": "mark class attendance, enter exam marks, assign homework, publish notices.",
            "Parent": "track child's attendance and academic performance, pay fee invoices, receive school notices.",
            "School Administrator": "manage admissions, allocate sections, assign teachers, configure fee structures.",
            "Accountant": "generate fee invoices, track payments, generate financial statements.",
            "Principal": "view aggregate performance reports, approve notices, manage school policies.",
        },
        domain_problems=[
            "Schools often manage student records, attendance, exams, fees, timetables, and parent communication using disconnected spreadsheets or paper-based processes.",
            "This causes delays, duplicate records, reporting errors, and weak visibility for administrators, teachers, students, and parents."
        ],
        business_goals=[
            "Digitize student admissions and profiles.",
            "Automate attendance tracking.",
            "Manage exams and marks.",
            "Generate report cards.",
            "Manage fee records.",
            "Improve parent-school communication.",
            "Centralize timetable and class management.",
        ],
        measurable_success_criteria=[
            "Timetable conflict check queries resolve under 300ms.",
            "100% of attendance entries are logged correctly.",
            "Zero duplicate fee invoices are generated per student.",
        ],
        entities=[
            "Student Profile",
            "Teacher Profile",
            "Class",
            "Subject",
            "Attendance Record",
            "Exam",
            "Marks",
            "Fee Invoice",
            "Timetable",
            "Assignment",
            "Notice",
            "Report Card",
        ],
        workflows=[
            "student admission",
            "class and section allocation",
            "attendance marking",
            "exam scheduling",
            "marks entry",
            "report card generation",
            "fee collection",
            "timetable management",
            "parent notification",
            "teacher assignment",
        ],
        modules=[
            "Admissions and Profiles",
            "Attendance Tracking",
            "Exams and Marks Management",
            "Fee Operations",
            "Timetable and Scheduling",
            "Communication and Notices",
        ],
        business_rules=[
            "Class assignment requires active student profile.",
            "Attendance must be submitted daily by assigned teachers.",
            "Marks can only be entered by authorized subject teachers.",
            "Report cards are generated only after principal approval.",
            "Fines are applied automatically to overdue fee invoices.",
        ],
        functional_requirements=[
            "FR-001 Student Admissions and Registration",
            "FR-002 Teacher Class Assignments",
            "FR-003 Daily Attendance Tracking",
            "FR-004 Exam Schedule and Marks Recording",
            "FR-005 Student Report Card Generation",
            "FR-006 Fee Invoice Collection",
            "FR-007 Notice Board Notifications",
        ],
        non_functional_requirements=[
            "Attendance record transaction consistency across classrooms.",
            "Report card generation response time under 1s for batches.",
            "Role-based access controls for student marks modification.",
            "Secure storage of student and family personal contact details.",
        ],
        feasibility_points={
            "technical": "Highly feasible. Relational database handles school records, classes, and marks. Attendance reporting is standard.",
            "operational": "Improves teacher efficiency and simplifies administrator workloads. Requires basic training for staff.",
            "economic": "Saves substantial paper costs and administrative hours.",
            "schedule": "6-week phased delivery.",
            "legal": "Complies with student record privacy guidelines.",
        },
        api_resources=[
            "/api/v1/admissions",
            "/api/v1/attendance",
            "/api/v1/exams",
            "/api/v1/fees",
            "/api/v1/notices",
        ],
        database_tables=[
            "students",
            "teachers",
            "classes",
            "subjects",
            "attendance",
            "exams",
            "marks",
            "fee_invoices",
            "timetables",
            "report_cards",
        ],
        reports=[
            "Daily Class Attendance Summary",
            "Term Exam Mark Sheet",
            "Fee Delinquency Ledger",
            "Student Performance History",
        ],
        risks=[
            "Incorrect marking of attendance.",
            "Unauthorized grade alteration by students.",
            "Double-booking classrooms in timetables.",
            "Loss of student transaction records.",
        ],
        assumptions=[
            "Teachers and students have web browsers.",
            "Data network is reliable.",
        ],
        constraints=[
            "Must meet strict academic privacy regulations.",
        ],
        out_of_scope=[
            "Online virtual classrooms and video streaming.",
            "School bus route GPS tracking.",
        ],
        primary_problem="Schools often manage student records, attendance, exams, fees, timetables, and parent communication using disconnected spreadsheets or paper-based processes. This causes delays, duplicate records, reporting errors, and weak visibility for administrators, teachers, students, and parents.",
        target_users=["Student", "Teacher", "Parent", "School Administrator", "Accountant", "Principal"],
        core_entities=["Student Profile", "Teacher Profile", "Class", "Subject", "Attendance Record", "Exam", "Marks", "Fee Invoice", "Timetable", "Assignment", "Notice", "Report Card"],
        core_workflows=["student admission", "class and section allocation", "attendance marking", "exam scheduling", "marks entry", "report card generation", "fee collection", "timetable management", "parent notification", "teacher assignment"],
        domain_risks=["Incorrect marking of attendance.", "Unauthorized grade alteration by students.", "Double-booking classrooms in timetables.", "Loss of student transaction records."],
    ),
    "gym-membership": DomainContext(
        project_name="Gym Membership Management System",
        normalized_domain="gym-membership",
        domain_type="Gym Membership Management",
        domain_summary=(
            "The Gym Membership Management System coordinates membership registration, member check-ins, "
            "workout plans, trainer scheduling, and subscription billing."
        ),
        institution_context="Fitness Center Operations Environment",
        primary_users=["Member", "Trainer"],
        secondary_users=["Gym Manager", "Receptionist"],
        actors=["Member", "Trainer", "Gym Manager", "Receptionist"],
        actors_with_responsibilities={
            "Member": "book workout slots, view active membership plans, log workout progress.",
            "Trainer": "manage workout schedules, assign exercise routines, track member goals.",
            "Gym Manager": "configure membership pricing, review club revenue reports, manage staff schedules.",
            "Receptionist": "register members, verify entry barcode scans, process payment transactions.",
        },
        domain_problems=[
            "Gyms struggle to track member check-ins, verify membership renewals, coordinate trainer calendars, and distribute workout schedules, leading to billing leakages."
        ],
        business_goals=[
            "Establish a digital membership registration.",
            "Provide automated checkout and trainer booking.",
            "Log check-ins and member attendance.",
            "Manage workout schedules and payment tracking.",
        ],
        measurable_success_criteria=[
            "Gate check-in barcode scans are verified under 200ms.",
            "Trainer calendar check resolves with zero conflicts.",
            "100% of subscription renewal payments are logged.",
        ],
        entities=[
            "Member Profile",
            "Trainer Profile",
            "Membership Plan",
            "Workout Schedule",
            "Payment Receipt",
            "CheckIn Log",
            "Exercise Routine",
            "Fitness Goal",
            "Attendance",
        ],
        workflows=[
            "Register gym member",
            "Purchase membership plan",
            "Log check-in scan",
            "Assign fitness trainer",
            "Create workout schedule",
            "Process renewal payment",
            "Track workout routine progress",
            "Log member attendance",
        ],
        modules=[
            "Membership Registry",
            "Subscription Billing",
            "Trainer Booking",
            "CheckIn Tracker",
            "Workout Planner",
        ],
        business_rules=[
            "Access is permitted only if membership is active.",
            "Workout sessions must be booked at least 2 hours in advance.",
            "Trainers cannot exceed 8 member allocations per slot.",
        ],
        functional_requirements=[
            "FR-001 Member Registration and Portals",
            "FR-002 Membership Plan Configuration",
            "FR-003 Check-in Scan Logging",
            "FR-004 Trainer Slot Booking",
            "FR-005 Routine Assignment and Progress Logging",
            "FR-006 Subscription Billing and Invoice Processing",
        ],
        non_functional_requirements=[
            "Check-in gate barcode scan latency under 200ms.",
            "Membership status verification transaction consistency.",
            "Secure storage of member credit card tokens.",
        ],
        feasibility_points={
            "technical": "Highly feasible. Scanner integration is standard, and billing uses subscription gateways (e.g. Stripe).",
            "operational": "Simplifies check-in workflows at gym reception.",
            "economic": "Prevents unpaid club access leakages, raising club revenues.",
            "schedule": "4-week phased delivery.",
            "legal": "Ensures compliance with member contact data laws.",
        },
        api_resources=[
            "/api/v1/members",
            "/api/v1/membership-plans",
            "/api/v1/checkins",
            "/api/v1/bookings",
            "/api/v1/payments",
        ],
        database_tables=[
            "members",
            "membership_plans",
            "trainers",
            "check_ins",
            "bookings",
            "payments",
            "workout_routines",
        ],
        reports=[
            "Active Membership Status List",
            "Daily Checkin Scan Log",
            "Monthly Club Revenue Report",
            "Trainer Utilization Sheet",
        ],
        risks=[
            "Unpaid member entry due to offline check-in gate.",
            "Double-booking trainer workout slots.",
            "Incorrect subscription renewal processing.",
        ],
        assumptions=[
            "Members carry active barcode/RFID cards.",
            "Payment processor webhooks are functional.",
        ],
        constraints=[
            "Uptime must match club operating hours.",
        ],
        out_of_scope=[
            "Selling energy drinks/supplements inventory.",
            "Controlling biometric door lock hardware directly.",
        ],
        primary_problem="Gyms struggle to track member check-ins, verify membership renewals, coordinate trainer calendars, and distribute workout schedules, leading to billing leakages.",
        target_users=["Member", "Trainer", "Gym Manager", "Receptionist"],
        core_entities=["Member Profile", "Trainer Profile", "Membership Plan", "Workout Schedule", "Payment Receipt", "CheckIn Log", "Exercise Routine", "Fitness Goal", "Attendance"],
        core_workflows=["Register gym member", "Purchase membership plan", "Log check-in scan", "Assign fitness trainer", "Create workout schedule", "Process renewal payment", "Track workout routine progress", "Log member attendance"],
        domain_risks=["Unpaid member entry due to offline check-in gate.", "Double-booking trainer workout slots.", "Incorrect subscription renewal processing."],
    ),
    "hostel-complaint": DomainContext(
        project_name="Hostel Complaint Management System",
        normalized_domain="hostel-complaint",
        domain_type="Hostel Complaint Management",
        domain_summary=(
            "The Hostel Complaint Management System registers hostel resident complaints, tracks room maintenance statuses, "
            "schedules repairs, and alerts wardens."
        ),
        institution_context="Hostel Accommodation Environment",
        primary_users=["Resident", "Maintenance Staff"],
        secondary_users=["Warden", "Hostel Administrator"],
        actors=["Resident", "Warden", "Maintenance Staff", "Hostel Administrator"],
        actors_with_responsibilities={
            "Resident": "file maintenance complaints, check room status, rate repair quality.",
            "Warden": "review student complaints, assign maintenance staff, audit completed work.",
            "Maintenance Staff": "update ticket status, record repair actions, request replacement parts.",
            "Hostel Administrator": "configure rooms, monitor response times, approve expense budgets.",
        },
        domain_problems=[
            "Hostel residents have no structured channel to report room maintenance issues, leading to delayed repairs and low tenant satisfaction."
        ],
        business_goals=[
            "Establish online resident complaint registration.",
            "Log room maintenance status updates.",
            "Coordinate maintenance staff and warden notifications.",
            "Improve response times for room repairs.",
        ],
        measurable_success_criteria=[
            "Urgent repair ticket alerts reach warden in under 1 minute.",
            "Average complaint resolution duration is cut by 40%.",
            "100% of repair expenses are logged against specific rooms.",
        ],
        entities=[
            "Resident Profile",
            "Warden Profile",
            "Hostel Room",
            "Complaint Ticket",
            "Maintenance Staff Profile",
            "Repair Detail",
            "Feedback Rating",
            "Complaint Status",
        ],
        workflows=[
            "File resident complaint",
            "Assign repair technician",
            "Update repair status",
            "Submit feedback rating",
            "Audit ticket duration",
            "Update complaint status",
        ],
        modules=[
            "Resident Portal",
            "Complaint Workflow",
            "Staff Scheduling",
            "Room Catalog",
            "Audit and Performance Dashboard",
        ],
        business_rules=[
            "Residents can only file complaints for their assigned rooms.",
            "Urgent complaints must alert wardens immediately.",
            "Tickets can only be closed after resident validation or warden approval.",
        ],
        functional_requirements=[
            "FR-001 Resident Complaint Submission",
            "FR-002 Room Allocation Verification",
            "FR-003 Complaint Status Transition Tracking",
            "FR-004 Technician Ticket Assignment",
            "FR-005 Repair Logging and Parts Entry",
            "FR-006 Feedback and Rating Collection",
        ],
        non_functional_requirements=[
            "Complaint submission latency under 200ms.",
            "Concurrent assignment consistency (no duplicate technician dispatch).",
            "Role-based access enforcing tenant profile privacy.",
        ],
        feasibility_points={
            "technical": "Highly feasible. Workflows use simple ticket state machines.",
            "operational": "Wardens gain automated dashboard visibility, ending manual logs.",
            "economic": "Reduces facility damage through rapid maintenance response.",
            "schedule": "4-week delivery.",
            "legal": "Complies with housing policy guidelines.",
        },
        api_resources=[
            "/api/v1/complaints",
            "/api/v1/rooms",
            "/api/v1/assignments",
            "/api/v1/technicians",
        ],
        database_tables=[
            "residents",
            "rooms",
            "complaints",
            "wardens",
            "technicians",
            "assignments",
            "feedbacks",
        ],
        reports=[
            "Average Ticket Resolve Time Report",
            "Open Maintenance Tickets Ledger",
            "Technician Workload Summary",
            "Room Issue Frequency Sheet",
        ],
        risks=[
            "Delayed repair of urgent water leakage/short-circuit issues.",
            "Loss of complaint logs during database outages.",
            "Unauthorized closure of active tickets.",
        ],
        assumptions=[
            "Residents have mobile browsers or portal access.",
            "Maintenance staff are equipped with smartphones.",
        ],
        constraints=[
            "System must notify technicians within minutes of high-priority tickets.",
        ],
        out_of_scope=[
            "Processing hostel rent transactions.",
            "Managing student food mess accounts.",
        ],
        primary_problem="Hostel residents have no structured channel to report room maintenance issues, leading to delayed repairs and low tenant satisfaction.",
        target_users=["Resident", "Warden", "Maintenance Staff", "Hostel Administrator"],
        core_entities=["Resident Profile", "Warden Profile", "Hostel Room", "Complaint Ticket", "Maintenance Staff Profile", "Repair Detail", "Feedback Rating", "Complaint Status"],
        core_workflows=["File resident complaint", "Assign repair technician", "Update repair status", "Submit feedback rating", "Audit ticket duration", "Update complaint status"],
        domain_risks=["Delayed repair of urgent water leakage/short-circuit issues.", "Loss of complaint logs during database outages.", "Unauthorized closure of active tickets."],
    ),
    "car-rental": DomainContext(
        project_name="Car Rental Platform",
        normalized_domain="car-rental",
        domain_type="Car Rental Platform",
        domain_summary=(
            "The Car Rental Platform manages vehicle inventory cataloging, customer booking requests, "
            "rental periods, payment authorizations, and vehicle return inspections."
        ),
        institution_context="Automotive Rental Business Environment",
        primary_users=["Customer", "Rental Agent"],
        secondary_users=["Fleet Manager", "Store Administrator"],
        actors=["Customer", "Rental Agent", "Fleet Manager", "Store Administrator"],
        actors_with_responsibilities={
            "Customer": "browse vehicle inventory, book rental periods, authorize payments, submit driver license.",
            "Rental Agent": "verify driver license, initiate vehicle check-out, log vehicle return inspections.",
            "Fleet Manager": "register vehicle profiles, track maintenance logs, manage car status.",
            "Store Administrator": "configure rental rates, review financial reports, manage user access.",
        },
        domain_problems=[
            "Car rental agencies suffer from double-booking vehicles, manual check-out/check-in inspection delays, untracked rental returns, and security risks with unpaid balances."
        ],
        business_goals=[
            "Establish a secure vehicle booking reservation.",
            "Support vehicle cataloging and fleet categorization.",
            "Track rental periods and payment authorization deposit holds.",
            "Verify returning vehicles through structured return inspections.",
        ],
        measurable_success_criteria=[
            "Vehicle availability state transitions are atomic.",
            "Return inspections are logged under 5 minutes at front desk.",
            "99.9% of card holds are pre-authorized before key pickup.",
        ],
        entities=[
            "Customer Profile",
            "Vehicle Record",
            "Booking Request",
            "Rental Transaction",
            "Payment Authorization",
            "Inspection Log",
            "Fleet Category",
        ],
        workflows=[
            "Search vehicle inventory",
            "Book rental period",
            "Authorize payment deposit",
            "Log check-out inspection",
            "Process vehicle return",
            "File damage check log",
        ],
        modules=[
            "Inventory Registry",
            "Reservation Flow",
            "Payment Gateway",
            "Inspection Audit Service",
            "Fleet Maintenance Log",
        ],
        business_rules=[
            "Vehicles can only be booked if status is active-available.",
            "Booking requires valid driver license verification.",
            "Return check-out logs must record mileage and fuel levels.",
        ],
        functional_requirements=[
            "FR-001 Vehicle Search and Filter",
            "FR-002 Booking Period Reservation",
            "FR-003 Payment Deposit Authorization",
            "FR-004 Check-out Verification",
            "FR-005 Return Mileage and Fuel Logging",
            "FR-006 Inspection Damage Checklist",
        ],
        non_functional_requirements=[
            "Vehicle status check transaction atomicity (ACID).",
            "License verification upload security.",
            "High availability during business rental shifts.",
        ],
        feasibility_points={
            "technical": "Highly feasible. Standard CRUD with calendar check queries.",
            "operational": "Streamlines the front desk vehicle checkout process.",
            "economic": "Increases fleet utilization rate and protects fleet valuation.",
            "schedule": "6-week delivery.",
            "legal": "Complies with vehicle rental contracts and insurance guidelines.",
        },
        api_resources=[
            "/api/v1/vehicles",
            "/api/v1/bookings",
            "/api/v1/inspections",
            "/api/v1/customers",
        ],
        database_tables=[
            "vehicles",
            "bookings",
            "inspections",
            "customers",
            "payments",
            "categories",
        ],
        reports=[
            "Fleet Utilization Summary",
            "Daily Rental Revenue Statement",
            "Vehicle Maintenance History Log",
            "Overdue Rental Returns List",
        ],
        risks=[
            "Double-booking of the same vehicle for overlapping periods.",
            "Rental of uninspected or damaged vehicles.",
            "Unpaid rental fees due to failed card pre-authorizations.",
        ],
        assumptions=[
            "Customers have valid driver licenses.",
            "Cars are physically cleaned between rentals.",
        ],
        constraints=[
            "Uptime must support mobile roadside booking access.",
        ],
        out_of_scope=[
            "Vehicle shipping and logistics between branches.",
            "Managing dealership purchasing contracts.",
        ],
        primary_problem="Car rental agencies suffer from double-booking vehicles, manual check-out/check-in inspection delays, untracked rental returns, and security risks with unpaid balances.",
        target_users=["Customer", "Rental Agent", "Fleet Manager", "Store Administrator"],
        core_entities=["Customer Profile", "Vehicle Record", "Booking Request", "Rental Transaction", "Payment Authorization", "Inspection Log", "Fleet Category"],
        core_workflows=["Search vehicle inventory", "Book rental period", "Authorize payment deposit", "Log check-out inspection", "Process vehicle return", "File damage check log"],
        domain_risks=["Double-booking of the same vehicle for overlapping periods.", "Rental of uninspected or damaged vehicles.", "Unpaid rental fees due to failed card pre-authorizations."],
    ),
    "blood-donation": DomainContext(
        project_name="Blood Donation Management System",
        normalized_domain="blood-donation",
        domain_type="Blood Donation Management",
        domain_summary=(
            "The Blood Donation Management System coordinates donor registrations, blood group inventories, "
            "donation camps, recipient requests, and safety screening logs."
        ),
        institution_context="Healthcare Blood Bank Operations Environment",
        primary_users=["Donor", "Staff Nurse"],
        secondary_users=["Blood Bank Manager", "Hospital Liaison"],
        actors=["Donor", "Staff Nurse", "Blood Bank Manager", "Hospital Liaison"],
        actors_with_responsibilities={
            "Donor": "register profile, check blood eligibility, book donation appointments.",
            "Staff Nurse": "record donor health vitals, log blood bag collections, track temperature storage.",
            "Blood Bank Manager": "monitor blood group stocks, track bag expiry dates, schedule donation camps.",
            "Hospital Liaison": "submit blood recipient requests, track emergency blood routing.",
        },
        domain_problems=[
            "Blood banks face difficulty tracking blood bag shelf-life, scheduling donors, organizing donation camps, and routing urgent blood bag requests to hospitals."
        ],
        business_goals=[
            "Establish donor registration and profile directories.",
            "Monitor blood group stocks and blood inventory levels.",
            "Log donor screening and safety tests.",
            "Coordinate blood donation camps and recipient request routing.",
        ],
        measurable_success_criteria=[
            "100% of blood bags are screened before marked ready.",
            "Inventory shelf-life alerts trigger 5 days before expiration.",
            "Emergency hospital requests receive stock check under 500ms.",
        ],
        entities=[
            "Donor Profile",
            "Donation Appointment",
            "Blood Bag Record",
            "Safety Screening Log",
            "Hospital Request",
            "Donation Camp Profile",
            "Blood Inventory Ledger",
        ],
        workflows=[
            "Register blood donor",
            "Screen donor eligibility",
            "Collect blood bag",
            "Log safety screening tests",
            "Fulfill blood recipient request",
            "Alert expired blood bags",
        ],
        modules=[
            "Donor Registry",
            "Appointment Booking",
            "Screening & Safety",
            "Blood Stock Inventory",
            "Hospital Request Routing",
        ],
        business_rules=[
            "Donors must wait at least 56 days between whole blood donations.",
            "Blood bags must be screened for infectious markers before distribution.",
            "Expired blood bags must be marked as biohazard-discarded.",
        ],
        functional_requirements=[
            "FR-001 Donor Registration and Portal",
            "FR-002 Vitals and Eligibility Screening",
            "FR-003 Blood Bag Labelling and Tracking",
            "FR-004 Safety Screening Result Logs",
            "FR-005 Hospital Recipient Requests",
            "FR-006 Blood Group Stock Counts",
            "FR-007 Expiry Alerts Notification",
        ],
        non_functional_requirements=[
            "Blood bag storage temperature alert delay under 1s.",
            "Donor medical screening privacy compliance.",
            "Traceability of blood bag from donor to recipient.",
        ],
        feasibility_points={
            "technical": "Highly feasible. Standard CRUD with strict validation schemas.",
            "operational": "Provides nurses with automated screening forms and expiry checks.",
            "economic": "Minimizes discarded blood units and saves lives.",
            "schedule": "6-week delivery.",
            "legal": "Strict health compliance rules (FDA/clinical regulations).",
        },
        api_resources=[
            "/api/v1/donors",
            "/api/v1/blood-bags",
            "/api/v1/screening",
            "/api/v1/requests",
            "/api/v1/camps",
        ],
        database_tables=[
            "donors",
            "blood_bags",
            "screenings",
            "requests",
            "camps",
            "inventory",
        ],
        reports=[
            "Blood Group Inventory Balance",
            "Discarded Expired Bag Logs",
            "Hospital Supply Fulfillment Ledger",
            "Donation Camp Participant Sheet",
        ],
        risks=[
            "Infection transmission due to unchecked blood bag screening status.",
            "Spoilage of blood inventory due to storage temperature fluctuations.",
            "Shortage of critical O-negative blood type during emergency requests.",
        ],
        assumptions=[
            "Donors answer screening questionnaires honestly.",
            "Refrigerators keep stable target temperatures.",
        ],
        constraints=[
            "Must comply with health safety guidelines for clinical fluid storage.",
        ],
        out_of_scope=[
            "Surgical blood transfusion operations at patient bedside.",
            "Organ transplant coordination.",
        ],
        primary_problem="Blood banks face difficulty tracking blood bag shelf-life, scheduling donors, organizing donation camps, and routing urgent blood bag requests to hospitals.",
        target_users=["Donor", "Staff Nurse", "Blood Bank Manager", "Hospital Liaison"],
        core_entities=["Donor Profile", "Donation Appointment", "Blood Bag Record", "Safety Screening Log", "Hospital Request", "Donation Camp Profile", "Blood Inventory Ledger"],
        core_workflows=["Register blood donor", "Screen donor eligibility", "Collect blood bag", "Log safety screening tests", "Fulfill blood recipient request", "Alert expired blood bags"],
        domain_risks=["Infection transmission due to unchecked blood bag screening status.", "Spoilage of blood inventory due to storage temperature fluctuations.", "Shortage of critical O-negative blood type during emergency requests."],
    ),
}
